delete from public.meme_files;
insert into public.meme_files (situation, path, original_name, sort) values
  ('second_item', 'memes/second_item/akh-mnk-anty-akh.jpg', 'اخ منك انتي اخ.jpg', 1),
  ('second_item', 'memes/second_item/argwk-blash-kda.jpg', 'ارجوك بلاش كدة.jfif', 2),
  ('second_item', 'memes/second_item/baaaaas-kfaya.jpg', 'باااااس كفاية.jpg', 3),
  ('second_item', 'memes/second_item/bs-yaaly.jpg', 'بس ياعلي.jpg', 4),
  ('second_item', 'memes/second_item/hbyby.jpg', 'حبيبي.jfif', 5),
  ('second_item', 'memes/second_item/hraaaaaam.jpg', 'حراااااام.jpg', 6),
  ('second_item', 'memes/second_item/ht-ht.webp', 'حط حط.webp', 7),
  ('second_item', 'memes/second_item/dahna-hnshwf-ayam-swda.jpg', 'داحنا هنشوف ايام سودة.jfif', 8),
  ('second_item', 'memes/second_item/dy-ayn-wsabtk.jpg', 'دي عين وصابتك.jpg', 9),
  ('second_item', 'memes/second_item/shghal-akl.jpg', 'شغال اكل.jpg', 10),
  ('second_item', 'memes/second_item/kfaya-bgaaaa.jpg', 'كفاية بجاااا.jpg', 11),
  ('second_item', 'memes/second_item/kfaya-yabyh.jpg', 'كفاية يابيه.jpg', 12),
  ('second_item', 'memes/second_item/kfaya-yasyd.jpg', 'كفاية ياسيد.jpg', 13),
  ('second_item', 'memes/second_item/mynfash.jpg', 'مينفعش.jpg', 14),
  ('second_item', 'memes/second_item/ha-ayh-tany.jpg', 'ها ايه تاني.jfif', 15),
  ('second_item', 'memes/second_item/wdah-yalmby.jpg', 'ودعه يالمبي.jpg', 16),
  ('many_items', 'memes/many_items/100-kalwry.jpg', '100 كالوري.jpg', 1),
  ('many_items', 'memes/many_items/argwk-blash-kda.jpg', 'ارجوك بلاش كدة.jfif', 2),
  ('many_items', 'memes/many_items/ana-khayf-awy-yahady.jpg', 'انا خايف اوي ياهادي.jfif', 3),
  ('many_items', 'memes/many_items/ahw-kyfy-kda.jpg', 'اهو كيفي كدة.jpg', 4),
  ('many_items', 'memes/many_items/ayh-yashykha.jpg', 'ايه ياشيخة.jfif', 5),
  ('many_items', 'memes/many_items/bkyza-wzghlwl.png', 'بكيزة وزغلول.png', 6),
  ('many_items', 'memes/many_items/kfaya-bgaaaa.jpg', 'كفاية بجاااا.jpg', 7),
  ('many_items', 'memes/many_items/kl-da-akl.jpg', 'كل دا اكل.jfif', 8),
  ('many_items', 'memes/many_items/mynfash.jpg', 'مينفعش.jpg', 9),
  ('cheese', 'memes/cheese/myn-aly-kl-algbna.jpg', 'مين الي كل الجبنة.jfif', 1),
  ('egg', 'memes/egg/100-kalwry.jpg', '100 كالوري.jpg', 1),
  ('egg', 'memes/egg/dsuout9xcae3rxu.webp', 'DSUoUt9XcAE3RXU.webp', 2),
  ('egg', 'memes/egg/fjzt99swiacclx3.jpg', 'FjZT99SWIAcCLx3.jfif', 3),
  ('egg', 'memes/egg/ana-btshaym.jpg', 'انا بتشائم.jpg', 4),
  ('egg', 'memes/egg/ana-khayf-awy-yahady.jpg', 'انا خايف اوي ياهادي.jfif', 5),
  ('egg', 'memes/egg/ayh-yashykha.jpg', 'ايه ياشيخة.jfif', 6),
  ('egg', 'memes/egg/baaaaas-kfaya.jpg', 'باااااس كفاية.jpg', 7),
  ('egg', 'memes/egg/gahzz.jpg', 'جاهزز.jfif', 8),
  ('egg', 'memes/egg/gtk-wksa-twksk.jpg', 'جتك وكسة توكسك.jfif', 9),
  ('egg', 'memes/egg/dwht.jpg', 'دوحت.jpg', 10),
  ('egg', 'memes/egg/fy-hyaty-mashwft-alhad-kda.jpg', 'في حياتي ماشوفت الحاد كدة.jpg', 11),
  ('egg', 'memes/egg/la-msh-ana.jpg', 'لا مش انا.jfif', 12),
  ('egg', 'memes/egg/layaragl.jpg', 'لاياراجل.jfif', 13),
  ('egg', 'memes/egg/mthlftsh-fy-alklam.jpg', 'متهلفطش في الكلام.jfif', 14),
  ('egg', 'memes/egg/mwwwd.jpg', 'مووود.jfif', 15),
  ('egg', 'memes/egg/mynfash.jpg', 'مينفعش.jpg', 16),
  ('egg', 'memes/egg/wdah-yalmby.jpg', 'ودعه يالمبي.jpg', 17),
  ('egg', 'memes/egg/yakhbr-abyd.jpg', 'ياخبر ابيض.jfif', 18),
  ('egg', 'memes/egg/yanas-yalwkal.webp', 'ياناس يالوكال.webp', 19),
  ('egg', 'memes/egg/yla-byna.jpg', 'يلا بينا.jpg', 20),
  ('foul', 'memes/foul/e73r3ikxibej0mkbthbha.jpg', 'E73R3ikXIBEJ0mkبتحبها.jpg', 1),
  ('foul', 'memes/foul/allh-allh.jpg', 'الله الله.jfif', 2),
  ('foul', 'memes/foul/ana-btshaym.jpg', 'انا بتشائم.jpg', 3),
  ('foul', 'memes/foul/hlawtk-yastmwny.webp', 'حلاوتك ياستموني.webp', 4),
  ('foul', 'memes/foul/shghal-akl.jpg', 'شغال اكل.jpg', 5),
  ('foul', 'memes/foul/ghryb-awy.jpg', 'غريب اوي.jfif', 6),
  ('foul', 'memes/foul/la-blash-kda.jpg', 'لا بلاش كدة.jpg', 7),
  ('foul', 'memes/foul/wgaha-wgaha.jpg', 'وجاهة وجاهة.jfif', 8),
  ('foul', 'memes/foul/yaayny-a-alhlw.jpg', 'ياعيني ع الحلو.jpg', 9),
  ('foul', 'memes/foul/yanas-yalwkal.webp', 'ياناس يالوكال.webp', 10),
  ('foul', 'memes/foul/ynyylk-yabw-syam.jpg', 'ينييلك يابو صيام.jpg', 11),
  ('potato', 'memes/potato/100-kalwry.jpg', '100 كالوري.jpg', 1),
  ('potato', 'memes/potato/e73r3ikxibej0mkbthbha.jpg', 'E73R3ikXIBEJ0mkبتحبها.jpg', 2),
  ('potato', 'memes/potato/aaml-nfsk-myt.jpg', 'اعمل نفسك ميت.jfif', 3),
  ('potato', 'memes/potato/alhlzwna.jpg', 'الحلزونة.jpeg', 4),
  ('potato', 'memes/potato/ana-aly-akhry.jpg', 'انا علي اخري.jfif', 5),
  ('potato', 'memes/potato/ahw-kyfy-kda.jpg', 'اهو كيفي كدة.jpg', 6),
  ('potato', 'memes/potato/ayh-almgtma-da.jpg', 'ايه المجتمع دا.jfif', 7),
  ('potato', 'memes/potato/ayh-yashykha.jpg', 'ايه ياشيخة.jfif', 8),
  ('potato', 'memes/potato/fy-hyaty-mashwft-alhad-kda.jpg', 'في حياتي ماشوفت الحاد كدة.jpg', 9),
  ('potato', 'memes/potato/lqd-antabny-alqsharyra.jpg', 'لقد انتابني القشعريرة.jpg', 10),
  ('potato', 'memes/potato/nhyn-hnwn.jpg', 'نهين هنون.jfif', 11),
  ('potato', 'memes/potato/waaaahda.png', 'وااااحدة.png', 12),
  ('potato', 'memes/potato/wgaha-wgaha.jpg', 'وجاهة وجاهة.jfif', 13),
  ('potato', 'memes/potato/yla-byna.jpg', 'يلا بينا.jpg', 14),
  ('taameya', 'memes/taameya/e73r3ikxibej0mkbthbha.jpg', 'E73R3ikXIBEJ0mkبتحبها.jpg', 1),
  ('taameya', 'memes/taameya/argwk-blash-kda.jpg', 'ارجوك بلاش كدة.jfif', 2),
  ('taameya', 'memes/taameya/brafw-yaam.jpg', 'برافو ياعم.jfif', 3),
  ('taameya', 'memes/taameya/gahzz.jpg', 'جاهزز.jfif', 4),
  ('taameya', 'memes/taameya/shklk-fahm.jpg', 'شكلك فاهم.jpg', 5),
  ('taameya', 'memes/taameya/yaayny-a-alhlw.jpg', 'ياعيني ع الحلو.jpg', 6),
  ('taameya', 'memes/taameya/yanas-yalwkal.webp', 'ياناس يالوكال.webp', 7),
  ('pay_one', 'memes/pay_one/alragl-da-hykhlyny-aayt.jpg', 'الراجل دا هيخليني اعيط.jfif', 1),
  ('remove', 'memes/remove/61aae06a-4028-441e-8647-038846066a2f.jpg', '61aae06a-4028-441e-8647-038846066a2f.jpg', 1),
  ('remove', 'memes/remove/argwk-blash-kda.jpg', 'ارجوك بلاش كدة.jfif', 2),
  ('remove', 'memes/remove/allh-allh.jpg', 'الله الله.jfif', 3),
  ('remove', 'memes/remove/ana-aly-akhry.jpg', 'انا علي اخري.jfif', 4),
  ('remove', 'memes/remove/anam-wla-akl.jpg', 'انام ولا اكل.jpg', 5),
  ('remove', 'memes/remove/baaaaas-kfaya.jpg', 'باااااس كفاية.jpg', 6),
  ('remove', 'memes/remove/hbyby.jpg', 'حبيبي.jfif', 7),
  ('remove', 'memes/remove/hraaaaaam.jpg', 'حراااااام.jpg', 8),
  ('remove', 'memes/remove/ht-ht.webp', 'حط حط.webp', 9),
  ('remove', 'memes/remove/shkra.jpg', 'شكرا.jpg', 10),
  ('remove', 'memes/remove/qwlt-kda.jpg', 'قولت كدة.jpg', 11),
  ('remove', 'memes/remove/la-askwz-my.png', 'لا اسكوز مي.png', 12),
  ('remove', 'memes/remove/nhyn-hnwn.jpg', 'نهين هنون.jfif', 13),
  ('idle', 'memes/idle/croe7njxeai4hrz.jpg', 'CrOE7NjXEAI4HRz.jpg', 1),
  ('idle', 'memes/idle/euvzsw2xcaean-g.jpg', 'EuVzSw2XcAEan-g.jpg', 2),
  ('idle', 'memes/idle/images-1.jpg', 'images (1).jpg', 3),
  ('idle', 'memes/idle/images-2.jpg', 'images (2).jfif', 4),
  ('idle', 'memes/idle/matntq-ybny.jpg', 'ماتنطق يبني.jpg', 5),
  ('idle', 'memes/idle/mmmm.jpg', 'مممم.jpg', 6),
  ('pay', 'memes/pay/a7lal.jpg', 'a7lal.jpg', 1),
  ('pay', 'memes/pay/e4fe4aa8-b272-46de-8395-d374fe45010f.jpg', 'e4fe4aa8-b272-46de-8395-d374fe45010f.jpg', 2),
  ('pay', 'memes/pay/images-1.jpg', 'images (1).jpg', 3),
  ('pay', 'memes/pay/images.jpg', 'images.jfif', 4),
  ('pay', 'memes/pay/images3.jpg', 'images3.jfif', 5),
  ('pay', 'memes/pay/adfa-hsab.jpg', 'ادفع حساب.jpg', 6),
  ('pay', 'memes/pay/adfalh-yabybrs.jpg', 'ادفعله يابيبرس.jpg', 7),
  ('pay', 'memes/pay/hsab-2.jpg', 'حساب 2.jpg', 8),
  ('pay', 'memes/pay/hsab.jpg', 'حساب.jpg', 9),
  ('pay', 'memes/pay/htdfa-hwryk.jpg', 'هتدفع هوريك.jfif', 10),
  ('delivered', 'memes/delivered/229325-almwzf-algaya.png', '229325-الموظف-الجائع.png', 1),
  ('delivered', 'memes/delivered/2haaaan.jpg', '2حعااان.jfif', 2),
  ('delivered', 'memes/delivered/2haaaan89.jpg', '2حعااان89.jpg', 3),
  ('delivered', 'memes/delivered/3haaaan.jpg', '3حعااان.jfif', 4),
  ('delivered', 'memes/delivered/5haaaan.jpg', '5حعااان.jpg', 5),
  ('delivered', 'memes/delivered/adfa-hsab.jpg', 'ادفع حساب.jpg', 6),
  ('delivered', 'memes/delivered/haaaan-4.jpg', 'حعااان 4.jpg', 7),
  ('delivered', 'memes/delivered/haaaan.jpg', 'حعااان.jpg', 8),
  ('delivered', 'memes/delivered/khmhaaaan-4.jpg', 'خمحعااان 4.jpg', 9),
  ('delivered', 'memes/delivered/msh-wakl.jpg', 'مش واكل.jpg', 10)
on conflict (situation, path) do update set original_name = excluded.original_name, sort = excluded.sort;
