-- El Shabrawy menu — printed prices + 2 EGP.
-- Bread: فينو / بلدي / شامي. Boxes: صغير / وسط / كبير. Plates: 2 بيض / 3 بيض.

insert into public.menu_categories (id, name, name_ar, tiered, sort) values
  ('foul', 'Foul Sandwiches', 'سندوتشات الفول', false, 1),
  ('taameya', 'Falafel Sandwiches', 'سندوتشات الطعمية', false, 2),
  ('oriental', 'Oriental Sandwiches', 'سندوتشات الشرقي', false, 3),
  ('omelet', 'Omelet Sandwiches', 'سندوتشات الأومليت', false, 4),
  ('omelet_plates', 'Omelet Plates', 'طلبات الأومليت', true, 5),
  ('meat', 'Meat Sandwiches', 'سندوتشات اللحوم', false, 6),
  ('green', 'Green Burger Taameya', 'جرين برجر طعمية', false, 7),
  ('rolls', 'Roll Sandwiches', 'سندوتشات الرول', false, 8),
  ('fries', 'Pomme Frites Sandwiches', 'سندوتشات بوم فريت', false, 9),
  ('apps', 'Appetizers', 'المقبلات', false, 10),
  ('misc', 'Assorted', 'منوع', false, 11),
  ('boxes', 'Boxes', 'العلب', true, 12)
on conflict (id) do update set name=excluded.name, name_ar=excluded.name_ar, tiered=excluded.tiered, sort=excluded.sort;

delete from public.menu_items;
delete from public.menu_categories where id not in ('foul', 'taameya', 'oriental', 'omelet', 'omelet_plates', 'meat', 'green', 'rolls', 'fries', 'apps', 'misc', 'boxes');

insert into public.menu_items
  (id, category_id, name, name_ar, price_shami, price_balady, price_fino, price_sm, price_md, price_lg, price_each, sort)
values
  ('foul-plain', 'foul', 'Foul', 'فول', 14, 14, 17, null, null, null, null, 1),
  ('foul-hot', 'foul', 'Foul Hot Oil', 'فول زيت حار', 14, 14, 17, null, null, null, null, 2),
  ('foul-olive', 'foul', 'Foul Olive Oil', 'فول زيت زيتون', 15, 15, 19, null, null, null, null, 3),
  ('foul-butter', 'foul', 'Foul Butter', 'فول زبدة', 15, 15, 19, null, null, null, null, 4),
  ('foul-alex', 'foul', 'Foul Alexandrian', 'فول اسكندراني', 15, 15, 19, null, null, null, null, 5),
  ('foul-lemon', 'foul', 'Foul Preserved Lemon', 'فول ليمون معصفر', 15, 15, 19, null, null, null, null, 6),
  ('foul-sug', 'foul', 'Foul Sausage', 'فول بالسجق', 20, 20, 24, null, null, null, null, 7),
  ('foul-egg', 'foul', 'Foul Boiled Egg', 'فول بالبيض المسلوق', 20, 20, 24, null, null, null, null, 8),
  ('foul-omelet', 'foul', 'Foul Omelet', 'فول بالبيض الأومليت', 20, 20, 24, null, null, null, null, 9),
  ('foul-baba', 'foul', 'Foul Baba Ghanoush', 'فول على بابا غنوج', 15, 15, 19, null, null, null, null, 10),
  ('foul-mesa', 'foul', 'Foul Moussaka', 'فول على مسقعة', 16, 16, 20, null, null, null, null, 11),
  ('foul-potato', 'foul', 'Foul Potato', 'فول على بطاطس', 17, 17, 21, null, null, null, null, 12),
  ('foul-salad', 'foul', 'Foul Salad', 'فول على سلطة', 16, 16, 19, null, null, null, null, 13),
  ('foul-bastr', 'foul', 'Foul Pastrami', 'فول بسطرمة', 22, 22, 26, null, null, null, null, 14),
  ('foul-eggpl', 'foul', 'Foul Eggplant', 'فول على باذنجان', 16, 16, 19, null, null, null, null, 15),
  ('tam-plain', 'taameya', 'Falafel', 'طعمية', 14, 14, 17, null, null, null, null, 1),
  ('tam-stuffed', 'taameya', 'Stuffed Falafel', 'طعمية محشية', 17, 17, 19, null, null, null, null, 2),
  ('tam-chick', 'taameya', 'Falafel Egg Inside', 'طعمية عين كتكوت', 20, 20, 24, null, null, null, null, 3),
  ('tam-omelet', 'taameya', 'Falafel Omelet', 'طعمية على أومليت', 20, 20, 24, null, null, null, null, 4),
  ('tam-egg', 'taameya', 'Falafel Boiled Egg', 'طعمية بالبيض المسلوق', 20, 20, 24, null, null, null, null, 5),
  ('tam-pickled-eggpl', 'taameya', 'Falafel Pickled Eggplant', 'طعمية بالباذنجان المخلل', 18, 18, 22, null, null, null, null, 6),
  ('tam-baba', 'taameya', 'Falafel Baba Ghanoush', 'طعمية على بابا غنوج', 19, 19, 21, null, null, null, null, 7),
  ('tam-white', 'taameya', 'Falafel White Cheese', 'طعمية على جبنة بيضاء', 19, 19, 23, null, null, null, null, 8),
  ('tam-old', 'taameya', 'Falafel Old Cheese', 'طعمية على جبنة قديمة', 19, 19, 23, null, null, null, null, 9),
  ('tam-roumi', 'taameya', 'Falafel Roumi', 'طعمية على جبنة رومي', 21, 21, 25, null, null, null, null, 10),
  ('tam-ched', 'taameya', 'Falafel Cheddar', 'طعمية على جبنة شيدر', 21, 21, 25, null, null, null, null, 11),
  ('tam-mozz', 'taameya', 'Falafel Mozzarella', 'طعمية على جبنة موتزاريلا', 21, 21, 25, null, null, null, null, 12),
  ('tam-mix', 'taameya', 'Falafel Mix Cheese', 'طعمية مكس جبن', 24, 24, 28, null, null, null, null, 13),
  ('tam-sug', 'taameya', 'Falafel Sausage', 'طعمية على سجق', 24, 24, 28, null, null, null, null, 14),
  ('tam-bastr', 'taameya', 'Falafel Pastrami', 'طعمية بالبسطرمة', 24, 24, 28, null, null, null, null, 15),
  ('tam-lemon', 'taameya', 'Falafel Preserved Lemon', 'طعمية على ليمون معصفر', 17, 17, 21, null, null, null, null, 16),
  ('tam-spicy', 'taameya', 'Spicy Falafel Harissa', 'طعمية مشطشطة بالهريسة', 20, 20, 24, null, null, null, null, 17),
  ('tam-kiri', 'taameya', 'Falafel Kiri', 'طعمية جبنة كيري', 24, 24, 26, null, null, null, null, 18),
  ('tam-saus', 'taameya', 'Falafel Hot Dog', 'طعمية على سوسيس', 24, 24, 26, null, null, null, null, 19),
  ('tam-fried-mix', 'taameya', 'Falafel Fried Mix', 'طعمية ميكس مقليات', 24, 24, 26, null, null, null, null, 20),
  ('tam-eggpl', 'taameya', 'Falafel Fried Eggplant', 'طعمية على باذنجان مقلي', 18, 18, 20, null, null, null, null, 21),
  ('tam-special', 'taameya', 'Special Falafel', 'طعمية مخصوص', 17, 17, 19, null, null, null, null, 22),
  ('ori-mesa', 'oriental', 'Moussaka', 'مسقعة', 17, 17, 21, null, null, null, null, 1),
  ('ori-baba', 'oriental', 'Baba Ghanoush', 'بابا غنوج', 17, 17, 21, null, null, null, null, 2),
  ('ori-eggpl', 'oriental', 'Fried Eggplant', 'باذنجان مقلي', 17, 17, 21, null, null, null, null, 3),
  ('ori-old', 'oriental', 'Old Cheese', 'جبنة قديمة', 17, 17, 21, null, null, null, null, 4),
  ('ori-white', 'oriental', 'White Cheese', 'جبنة بيضاء', 17, 17, 21, null, null, null, null, 5),
  ('ori-tomato', 'oriental', 'Cheese Tomato Cucumber Olive', 'جبنة بالطماطم والخيار وزيت الزيتون', 20, 20, 24, null, null, null, null, 6),
  ('ori-fries', 'oriental', 'Fried Potatoes', 'بطاطس محمرة', 17, 17, 21, null, null, null, null, 7),
  ('ori-pomme', 'oriental', 'Pomme Frites', 'بطاطس بوم فريت', 24, 24, 28, null, null, null, null, 8),
  ('ori-chips', 'oriental', 'Chips', 'بطاطس شيبسي', 17, 17, 21, null, null, null, null, 9),
  ('ori-mash', 'oriental', 'Mashed Potatoes', 'بطاطس مهروسة', 17, 17, 21, null, null, null, null, 10),
  ('ori-mash-egg', 'oriental', 'Mashed with Egg', 'بطاطس مهروسة بالبيض', 27, 27, 29, null, null, null, null, 11),
  ('ori-mash-omelet', 'oriental', 'Mashed Fried Egg', 'بطاطس مهروسة ببيض مقلي', 27, 27, 29, null, null, null, null, 17),
  ('ori-mash-bastr', 'oriental', 'Mashed with Pastrami', 'بطاطس مهروسة بالبسطرمة', 32, 32, 36, null, null, null, null, 12),
  ('ori-pomme-roumi', 'oriental', 'Fries Roumi Olive', 'بطاطس بوم فريت بالرومي والزيتون', 32, 32, 36, null, null, null, null, 13),
  ('ori-dynamite', 'oriental', 'Dynamite Mix', 'ديناميت', 27, 27, 31, null, null, null, null, 14),
  ('ori-shak', 'oriental', 'Shakshouka', 'شكشوكة', 17, 17, 21, null, null, null, null, 15),
  ('ori-thyme', 'oriental', 'Cheese Thyme Olive Oil', 'جبنة بالزعتر وزيت الزيتون', 18, 18, 22, null, null, null, null, 16),
  ('om-plain', 'omelet', 'Plain Omelet', 'أومليت سادة', 19, 19, 23, null, null, null, null, 1),
  ('om-bastr', 'omelet', 'Omelet Pastrami', 'أومليت بالبسطرمة', 25, 25, 29, null, null, null, null, 2),
  ('om-sug', 'omelet', 'Omelet Sausage', 'أومليت بالسجق', 25, 25, 29, null, null, null, null, 3),
  ('om-pizza', 'omelet', 'Omelet Pizza', 'أومليت بيتزا', 25, 25, 29, null, null, null, null, 4),
  ('om-kiri', 'omelet', 'Omelet Kiri', 'أومليت كيري', 25, 25, 29, null, null, null, null, 5),
  ('om-roumi', 'omelet', 'Omelet Roumi', 'أومليت رومي', 28, 28, 32, null, null, null, null, 6),
  ('om-ched', 'omelet', 'Omelet Cheddar', 'أومليت شيدر', 28, 28, 32, null, null, null, null, 7),
  ('om-mozz', 'omelet', 'Omelet Mozzarella', 'أومليت موتزاريلا', 28, 28, 32, null, null, null, null, 8),
  ('om-mix', 'omelet', 'Omelet Mix Cheese', 'أومليت مكس جبن', 30, 30, 34, null, null, null, null, 9),
  ('om-boiled', 'omelet', 'Boiled Egg Sandwich', 'بيض مسلوق', 18, 18, 22, null, null, null, null, 10),
  ('om-roll', 'omelet', 'Egg Rolled in Butter', 'بيض دحروجة في الزبدة', 22, 22, 26, null, null, null, null, 11),
  ('om-veg', 'omelet', 'Vegetable Omelet', 'أومليت خضروات', 21, 21, 25, null, null, null, null, 12),
  ('om-saus', 'omelet', 'Omelet Hot Dog', 'أومليت سوسيس', 25, 25, 29, null, null, null, null, 13),
  ('green-plain', 'green', 'Plain Green Burger', 'جرين برجر سادة', 17, 20, null, null, null, null, null, 1),
  ('green-stuffed', 'green', 'Stuffed Green Burger', 'جرين برجر محشية', 20, 22, null, null, null, null, null, 2),
  ('green-bastr', 'green', 'Green Burger Pastrami', 'جرين برجر بسطرمة', 22, 24, null, null, null, null, null, 3),
  ('green-mix', 'green', 'Green Burger Mix Cheese', 'جرين برجر ميكس جبن', 24, 26, null, null, null, null, null, 4),
  ('green-kiri', 'green', 'Green Burger Kiri', 'جرين برجر جبنة كيري', 21, 23, null, null, null, null, null, 5),
  ('green-egg', 'green', 'Green Burger Egg', 'جرين برجر بيض', 22, 24, null, null, null, null, null, 6),
  ('green-egg-cheese', 'green', 'Green Burger Egg & Cheese', 'جرين برجر بيض و جبنة', 28, 28, null, null, null, null, null, 7),
  ('fr-plain', 'fries', 'Pomme Frites', 'بوم فريت', 20, null, 23, null, null, null, null, 1),
  ('fr-ketch', 'fries', 'Fries Ketchup', 'بوم فريت كاتشب', 21, null, 24, null, null, null, null, 2),
  ('fr-mayo', 'fries', 'Fries Mayo', 'بوم فريت مايونيز', 21, null, 24, null, null, null, null, 3),
  ('fr-ketch-mayo', 'fries', 'Fries Ketchup Mayo', 'بوم فريت كاتشب مايونيز', 22, null, 25, null, null, null, null, 4),
  ('fr-egg', 'fries', 'Fries Boiled Egg', 'بوم فريت على بيض مسلوق', 24, null, 28, null, null, null, null, 5),
  ('fr-omelet', 'fries', 'Fries Omelet', 'بوم فريت على أومليت', 24, null, 28, null, null, null, null, 6),
  ('fr-white', 'fries', 'Fries White Cheese', 'بوم فريت على جبنة بيضاء', 24, null, 28, null, null, null, null, 7),
  ('fr-roumi', 'fries', 'Fries Roumi', 'بوم فريت على جبنة رومي', 24, null, 28, null, null, null, null, 8),
  ('fr-ched', 'fries', 'Fries Cheddar', 'بوم فريت على جبنة شيدر', 24, null, 28, null, null, null, null, 9),
  ('fr-mozz', 'fries', 'Fries Mozzarella', 'بوم فريت على جبنة موتزاريلا', 26, null, 30, null, null, null, null, 10),
  ('fr-mix', 'fries', 'Fries Mix Cheese', 'بوم فريت على ميكس جبن', 24, null, 28, null, null, null, null, 11),
  ('fr-feta', 'fries', 'Fries Feta', 'بوم فريت على جبنة فيتا', 21, null, 25, null, null, null, null, 12),
  ('fr-qarish', 'fries', 'Fries Cottage Cheese', 'بوم فريت على جبنة قريش', 21, null, 25, null, null, null, null, 13),
  ('fr-baba', 'fries', 'Fries Baba Ghanoush', 'بوم فريت على بابا غنوج', 21, null, 25, null, null, null, null, 14),
  ('fr-eggpl', 'fries', 'Fries Fried Eggplant', 'بوم فريت على باذنجان مقلي', 21, null, 25, null, null, null, null, 15),
  ('fr-pickled-eggpl', 'fries', 'Fries Pickled Eggplant', 'بوم فريت على باذنجان مخلل', 21, null, 25, null, null, null, null, 16),
  ('fr-saus', 'fries', 'Fries Sausage', 'بوم فريت على سوسيس', 29, null, 34, null, null, null, null, 17),
  ('fr-bazooka', 'fries', 'Bazooka', 'بازوكا', 20, null, 24, null, null, null, null, 18),
  ('fr-chips', 'fries', 'Potato Chips', 'بطاطس شيبسي', 20, null, 24, null, null, null, null, 19),
  ('fr-mash', 'fries', 'Mashed Potatoes', 'بطاطس مهروسة', 20, null, 24, null, null, null, null, 20),
  ('fr-panne', 'fries', 'Potato Pané', 'بطاطس بانيه', 28, null, 32, null, null, null, null, 21),
  ('fr-mash-butter', 'fries', 'Mashed with Butter', 'مهروسة بالزبدة', 29, null, 34, null, null, null, null, 22),
  ('fr-mash-egg', 'fries', 'Mashed Boiled Egg', 'مهروسة على بيض مسلوق', 21, null, 25, null, null, null, null, 23),
  ('fr-mash-omelet', 'fries', 'Mashed Omelet', 'مهروسة على أومليت', 22, null, 26, null, null, null, null, 24),
  ('fr-mash-bastr', 'fries', 'Mashed Pastrami', 'مهروسة على بسطرمة', 24, null, 28, null, null, null, null, 25),
  ('fr-chips-ketch', 'fries', 'Chips Ketchup', 'شيبسي كاتشب', 24, null, 28, null, null, null, null, 26),
  ('fr-chips-mayo', 'fries', 'Chips Mayo', 'شيبسي مايونيز', 25, null, 29, null, null, null, null, 27),
  ('fr-chips-mix', 'fries', 'Chips Ketchup Mayo', 'شيبسي كاتشب و مايونيز', 21, null, 25, null, null, null, null, 28),
  ('fr-panne-mix', 'fries', 'Pané Ketchup Mayo', 'بانيه كاتشب و مايونيز', 23, null, 27, null, null, null, null, 29),
  ('meat-liver', 'meat', 'Liver', 'كبدة', null, null, null, null, null, null, 32, 1),
  ('meat-sug', 'meat', 'Sausage', 'سجق', null, null, null, null, null, null, 32, 2),
  ('meat-burger', 'meat', 'Plain Burger', 'برجر سادة', null, null, null, null, null, null, 52, 3),
  ('meat-burger-egg', 'meat', 'Burger Egg', 'برجر بيض', null, null, null, null, null, null, 62, 4),
  ('meat-burger-cheese', 'meat', 'Burger Cheese', 'برجر جبنة', null, null, null, null, null, null, 67, 5),
  ('meat-burger-mix', 'meat', 'Mix Burger Egg & Cheese', 'برجر ميكس بيض و جبنة', null, null, null, null, null, null, 72, 6),
  ('meat-hawawshi', 'meat', 'Hawawshi', 'حواوشي', null, null, null, null, null, null, 52, 7),
  ('roll-foul', 'rolls', 'Foul Rockets Roll', 'رول صواريخ ف.م', null, null, null, null, null, null, 32, 1),
  ('roll-tam', 'rolls', 'Taameya Rockets Roll', 'رول صواريخ ت.ك', null, null, null, null, null, null, 32, 2),
  ('roll-potato', 'rolls', 'Potato Rockets Roll', 'رول صواريخ بطاطس ك.م', null, null, null, null, null, null, 37, 3),
  ('roll-mix', 'rolls', 'Mix Cheese Rockets Roll', 'رول صواريخ ميكس جبن', null, null, null, null, null, null, 42, 4),
  ('roll-mozz', 'rolls', 'Mozzarella Rockets Roll', 'رول صواريخ موتزاريلا', null, null, null, null, null, null, 47, 5),
  ('roll-pepper', 'rolls', 'Pepper Mix Cheese Roll', 'رول صواريخ فلفل ميكس جبن', null, null, null, null, null, null, 42, 6),
  ('roll-saus', 'rolls', 'Sausage Rockets Roll', 'رول صواريخ سوسيس', null, null, null, null, null, null, 52, 7),
  ('roll-bastr', 'rolls', 'Pastrami Rockets Roll', 'رول صواريخ بسطرمة', null, null, null, null, null, null, 57, 8),
  ('roll-sug', 'rolls', 'Sojouk Rockets Roll', 'رول صواريخ سجق', null, null, null, null, null, null, 57, 9),
  ('roll-om-mix', 'rolls', 'Omelet Mix Cheese Roll', 'رول أومليت ميكس جبن', null, null, null, null, null, null, 52, 10),
  ('roll-falafel-mix', 'rolls', 'Falafel Mix Cheese Roll', 'رول فلافل ميكس جبن', null, null, null, null, null, null, 42, 11),
  ('roll-shabrawy', 'rolls', 'El Shabrawy Roll', 'رول الشبراوي', null, null, null, null, null, null, 62, 12),
  ('roll-om-saus', 'rolls', 'Omelet Sausage Roll', 'رول أومليت سوسيس', null, null, null, null, null, null, 52, 13),
  ('roll-liver', 'rolls', 'Liver Roll', 'رول كبدة', null, null, null, null, null, null, 52, 14),
  ('app-lemon', 'apps', 'Preserved Lemon Box', 'علبة ليمون معصفر', null, null, null, null, null, null, 12, 1),
  ('app-olives', 'apps', 'Pickled Olives Box', 'علبة زيتون مخلل', null, null, null, null, null, null, 12, 2),
  ('app-cucumber', 'apps', 'Pickled Cucumber Box', 'علبة خيار مخلل', null, null, null, null, null, null, 13, 3),
  ('app-mix-pickle', 'apps', 'Mixed Pickles Box', 'علبة مخلل مشكل', null, null, null, null, null, null, 9, 4),
  ('app-tomato', 'apps', 'Pickled Tomatoes Box', 'علبة طماطم مخلل', null, null, null, null, null, null, 12, 5),
  ('app-eggpl-pick', 'apps', 'Pickled Eggplant Box', 'علبة باذنجان مخلل', null, null, null, null, null, null, 13, 6),
  ('app-eggpl-fried', 'apps', 'Fried Eggplant Box', 'علبة باذنجان مقلي', null, null, null, null, null, null, 13, 7),
  ('app-salad', 'apps', 'Local Salad Box', 'علبة سلطة بلدي', null, null, null, null, null, null, 13, 8),
  ('app-tahini', 'apps', 'Tahini Box', 'علبة طحينة', null, null, null, null, null, null, 13, 9),
  ('app-pickles-plate', 'apps', 'Pickles Plate', 'طبق طرشي', null, null, null, null, null, null, 18, 10),
  ('app-omelet', 'apps', 'Omelet Box', 'علبة أومليت', null, null, null, null, null, null, 14, 11),
  ('app-pepper', 'apps', 'Fried Pepper Box', 'علبة فلفل مقلي', null, null, null, null, null, null, 13, 12),
  ('app-toum', 'apps', 'Toumeya Box', 'علبة ثومية', null, null, null, null, null, null, 18, 13),
  ('misc-disc', 'misc', 'Falafel Piece', 'قرص طعمية', null, null, null, null, null, null, 5, 1),
  ('misc-disc-stuffed', 'misc', 'Stuffed Falafel Piece', 'قرص طعمية محشية', null, null, null, null, null, null, 7, 2),
  ('misc-disc-chick', 'misc', 'Falafel Piece Egg Inside', 'قرص طعمية عين كتكوت', null, null, null, null, null, null, 14, 3),
  ('misc-fries-pack', 'misc', 'Fries Packet', 'باكيت بطاطس بوم فريت', null, null, null, null, null, null, 20, 4),
  ('misc-egg', 'misc', 'Boiled Egg', 'بيضة مسلوقة', null, null, null, null, null, null, 12, 5),
  ('misc-shami-loaf', 'misc', 'Shami Loaf', 'رغيف شامي', null, null, null, null, null, null, 3.5, 6),
  ('misc-balady-loaf', 'misc', 'Balady Loaf', 'رغيف بلدي', null, null, null, null, null, null, 5.5, 7),
  ('misc-disc-roumi', 'misc', 'Falafel Piece Roumi', 'قرص طعمية جبنة رومي', null, null, null, null, null, null, 14, 8),
  ('misc-disc-ched', 'misc', 'Falafel Piece Cheddar', 'قرص طعمية جبنة شيدر', null, null, null, null, null, null, 14, 9),
  ('misc-disc-mozz', 'misc', 'Falafel Piece Mozzarella', 'قرص طعمية جبنة موتزاريلا', null, null, null, null, null, null, 15, 10),
  ('misc-disc-mix', 'misc', 'Falafel Piece Mix Cheese', 'قرص طعمية ميكس جبن', null, null, null, null, null, null, 17, 11),
  ('plt-plain', 'omelet_plates', 'Plain Omelet Plate', 'أومليت سادة', null, null, null, 18, 26, null, null, 1),
  ('plt-special', 'omelet_plates', 'Special Omelet Plate', 'أومليت استبيشال', null, null, null, 21, 28, null, null, 2),
  ('plt-bastr', 'omelet_plates', 'Pastrami Omelet Plate', 'أومليت بسطرمة', null, null, null, 23, 30, null, null, 3),
  ('plt-sug', 'omelet_plates', 'Sausage Omelet Plate', 'أومليت بالسجق', null, null, null, 23, 30, null, null, 4),
  ('plt-pizza', 'omelet_plates', 'Pizza Omelet Plate', 'أومليت بيتزا', null, null, null, 25, 32, null, null, 5),
  ('plt-roumi', 'omelet_plates', 'Roumi Omelet Plate', 'أومليت رومي', null, null, null, 25, 32, null, null, 6),
  ('plt-ched', 'omelet_plates', 'Cheddar Omelet Plate', 'أومليت شيدر', null, null, null, 22, 29, null, null, 7),
  ('plt-mozz', 'omelet_plates', 'Mozzarella Omelet Plate', 'أومليت موتزاريلا', null, null, null, 22, 29, null, null, 8),
  ('plt-mix', 'omelet_plates', 'Mix Cheese Omelet Plate', 'أومليت مكس جبن', null, null, null, 26, 33, null, null, 9),
  ('box-plain', 'boxes', 'Plain Foul Box', 'علبة فول سادة', null, null, null, 14, 24, 30, null, 1),
  ('box-alex', 'boxes', 'Alexandrian Foul Box', 'علبة فول اسكندراني', null, null, null, 17, 28, 35, null, 2),
  ('box-olive', 'boxes', 'Olive Oil Foul Box', 'علبة فول زيت زيتون', null, null, null, 18, 28, 35, null, 3),
  ('box-sug', 'boxes', 'Sausage Foul Box', 'علبة فول بالسجق', null, null, null, 21, 31, 41, null, 4),
  ('box-mesa', 'boxes', 'Moussaka Box', 'علبة مسقعة', null, null, null, 17, 26, 37, null, 5),
  ('box-baba', 'boxes', 'Baba Ghanoush Box', 'علبة بابا غنوج', null, null, null, 17, 26, 36, null, 6),
  ('box-old', 'boxes', 'Old Cheese Box', 'علبة جبنة قديمة', null, null, null, 17, 26, 36, null, 7),
  ('box-toum', 'boxes', 'Toumeya Box', 'علبة تومية', null, null, null, null, 18, 26, null, 8),
  ('box-taameya', 'boxes', 'Falafel Dough Box', 'علبة عجينة طعمية', null, null, null, null, 21, 27, null, 9),
  ('box-hotoil', 'boxes', 'Hot Oil Foul Box', 'علبة فول زيت حار', null, null, null, 17, 27, 35, null, 10),
  ('box-lemon', 'boxes', 'Preserved Lemon Foul Box', 'علبة فول ليمون معصفر', null, null, null, 18, 28, 36, null, 11),
  ('box-bastr', 'boxes', 'Pastrami Foul Box', 'علبة فول بسطرمة', null, null, null, 21, 31, 41, null, 12),
  ('box-butter', 'boxes', 'Butter Foul Box', 'علبة فول بالزبدة', null, null, null, 19, 28, 35, null, 13),
  ('box-mash', 'boxes', 'Mashed Box', 'علبة مهروسة', null, null, null, 17, 22, 27, null, 14),
  ('box-mash-bastr', 'boxes', 'Mashed Pastrami Box', 'علبة مهروسة بسطرمة', null, null, null, 22, 32, 42, null, 15),
  ('box-feta', 'boxes', 'Feta Box', 'علبة جبنة فيتا', null, null, null, 17, 26, 36, null, 16),
  ('box-thyme', 'boxes', 'Thyme Cheese Box', 'علبة جبنة زعتر وزيت زيتون', null, null, null, 19, 27, 37, null, 17);
