/** أفيهات أفلام ومسلسلات مصرية — واحدة لكل صنف */
const FALLBACK = { text: "الجوع كافر", from: "مثل مصري / السينما" };

const AFEYAT = {
  "foul-plain": { text: "الجوع كافر", from: "مثل مصري" },
  "foul-special": { text: "أنا الأصل والباقي تقليد", from: "إسماعيل ياسين" },
  "foul-salsa": { text: "يا نهار أسود", from: "عادل إمام" },
  "foul-alex": { text: "إسكندرية ليه", from: "يوسف شاهين" },
  "foul-hot": { text: "هتولع يا عم", from: "اللمبي" },
  "foul-olive": { text: "بالهنا والشفا", from: "كلاسيك السينما المصرية" },
  "foul-corn": { text: "يا primitive", from: "تيمور وشفيقة" },
  "foul-butter": { text: "كده رضا", from: "كده رضا" },
  "foul-ghee": { text: "أكل العيش يا معلم", from: "أفيهات السينما" },
  "foul-egg": { text: "إنجليزي ده يا مرسي؟", from: "مدرسة المشاغبين" },
  "foul-omelet": { text: "ثواني ثواني", from: "سمير وشهير وبهير" },
  "foul-bastr": { text: "على مسئوليتي", from: "أفلام الأكشن المصرية" },
  "foul-sug": { text: "محدش يتحرك", from: "أفلام الأكشن المصرية" },
  "foul-meat": { text: "عايز كباب", from: "الإرهاب والكباب" },
  "foul-tahina": { text: "كده يا شيخ", from: "اللمبي" },

  "tam-plain": { text: "اديني عقلك", from: "اللمبي" },
  "tam-special": { text: "أنا اللمبي", from: "اللمبي" },
  "tam-stuffed": { text: "يا عم الحج", from: "اللمبي / الكبير أوي" },
  "tam-egg": { text: "آسف على الإزعاج", from: "آسف على الإزعاج" },
  "tam-omelet": { text: "يا خبر أبيض", from: "عادل إمام" },
  "tam-kiri": { text: "يا واد يا حلو", from: "كلاسيك السينما" },
  "tam-bastr": { text: "هتخش النار يا جدع", from: "اللمبي" },
  "tam-fingers": { text: "أقف؟ أقف", from: "مدرسة المشاغبين" },
  "tam-chips": { text: "يا primitive", from: "تيمور وشفيقة" },
  "tam-mozz": { text: "يا سلام", from: "إسماعيل ياسين" },
  "tam-eggpl": { text: "هيه أبويا اتحرق", from: "مدرسة المشاغبين" },

  "bat-fingers": { text: "الكبير أوي", from: "الكبير أوي" },
  "bat-chips": { text: "جوني جوني", from: "الكبير أوي" },
  "bat-puree": { text: "المزريطة", from: "الكبير أوي" },
  "bat-panne": { text: "يا عم أنا صعيدي", from: "صعيدي في الجامعة الأمريكية" },
  "bat-ketch": { text: "كده يا شيخ", from: "اللمبي" },
  "bat-mayo": { text: "معلش يا باشا", from: "عادل إمام" },
  "bat-mix": { text: "من الآخر كده", from: "أفيهات مصرية" },
  "bat-ched": { text: "حاضر يا بيه", from: "الواد سيد الشغال" },
  "bat-roumi": { text: "الواد سيد الشغال", from: "الواد سيد الشغال" },
  "bat-boiled": { text: "أنا ما شفتش حاجة", from: "شاهد ما شافش حاجة" },
  "bat-omelet": { text: "سيبها على الله", from: "أفلام مصرية" },
  "bat-shrimp": { text: "السفارة في العمارة", from: "السفارة في العمارة" },

  "egg-roll": { text: "يا نهار أسود", from: "عادل إمام" },
  "egg-boiled": { text: "بعد 14 سنة خدمة", from: "مدرسة المشاغبين" },
  "egg-omelet": { text: "آسف على الإزعاج", from: "آسف على الإزعاج" },
  "egg-bastr": { text: "طيور الظلام", from: "طيور الظلام" },
  "egg-roumi": { text: "مرجان أحمد مرجان", from: "مرجان أحمد مرجان" },
  "egg-ched": { text: "عمارة يعقوبيان", from: "عمارة يعقوبيان" },
  "egg-saus": { text: "حسن ومرقص", from: "حسن ومرقص" },
  "egg-chez-tom": { text: "واحدة بواحدة", from: "واحدة بواحدة" },

  "misc-eggpl": { text: "هيه أبويا اتحرق", from: "مدرسة المشاغبين" },
  "misc-baba": { text: "بابا عايز كده", from: "بابا عايز كده" },
  "misc-tomato": { text: "سلام يا صاحبي", from: "سلام يا صاحبي" },
  "misc-french": { text: "يا عم أنا صعيدي", from: "صعيدي في الجامعة الأمريكية" },
  "misc-mesa": { text: "إحنا بتوع الأتوبيس", from: "إحنا بتوع الأتوبيس" },
  "misc-mesa-mt": { text: "لصوص لكن ظرفاء", from: "لصوص لكن ظرفاء" },
  "misc-mesa-sg": { text: "المشبوه", from: "المشبوه" },
  "misc-shak": { text: "عسل أسود", from: "عسل أسود" },
  "misc-egga": { text: "يا عم الحج", from: "الكبير أوي" },
  "misc-fried": { text: "الأفوكاتو", from: "الأفوكاتو" },

  "box-plain": { text: "الجوع كافر", from: "مثل مصري" },
  "box-mahmoug": { text: "اللمبي 8 جيجا", from: "اللمبي 8 جيجا" },
  "box-hotoil": { text: "هتولع يا عم", from: "اللمبي" },
  "box-olive": { text: "بالهنا والشفا", from: "كلاسيك السينما المصرية" },
  "box-corn": { text: "يا primitive", from: "تيمور وشفيقة" },
  "box-butter": { text: "كده رضا", from: "كده رضا" },
  "box-sausage": { text: "عايز كباب", from: "الإرهاب والكباب" },
  "box-ghee": { text: "أكل العيش يا معلم", from: "أفيهات السينما" },
  "box-meat": { text: "الإرهاب والكباب", from: "الإرهاب والكباب" },
  "box-bastr": { text: "على مسئوليتي", from: "أفلام الأكشن المصرية" },
  "box-tahina": { text: "كده يا شيخ", from: "اللمبي" },
  "box-tesha": { text: "يا عم الحج", from: "اللمبي / الكبير أوي" },
  "box-mesa": { text: "إحنا بتوع الأتوبيس", from: "إحنا بتوع الأتوبيس" },
  "box-batpur": { text: "الكبير أوي", from: "الكبير أوي" },
  "box-baba": { text: "بابا عايز كده", from: "بابا عايز كده" },
  "box-shak": { text: "عسل أسود", from: "عسل أسود" },
  "box-mesa-mt": { text: "طيور الظلام", from: "طيور الظلام" },
  "box-mesa-sg": { text: "المشبوه", from: "المشبوه" },
  "box-mesa-so": { text: "حسن ومرقص", from: "حسن ومرقص" },
  "box-taameya": { text: "اديني عقلك", from: "اللمبي" },
};

export function afeya(id) {
  return AFEYAT[id] || FALLBACK;
}
