/** أفيهات قصيرة لايقة على اسم الصنف — مش جملة واحدة على المنيو كله */
const POOL = [
  { text: "كده يا معلم", from: "أفيهات مصرية" },
  { text: "يلا بينا ناكل", from: "أفيهات مصرية" },
  { text: "صباح الفل", from: "كلاسيك السينما" },
  { text: "عيش يا كده", from: "أفيهات مصرية" },
];

const AFEYAT = {
  "foul-plain": { text: "قوم كل يا باشا", from: "أفيهات مصرية" },
  "foul-hot": { text: "هتولع يا عم", from: "اللمبي" },
  "foul-olive": { text: "بالهنا والشفا", from: "كلاسيك السينما المصرية" },
  "foul-butter": { text: "كده رضا", from: "كده رضا" },
  "foul-alex": { text: "إسكندرية ليه", from: "يوسف شاهين" },
  "foul-lemon": { text: "حامض يا لمون", from: "أفيهات مصرية" },
  "foul-sug": { text: "محدش يتحرك", from: "أفلام الأكشن المصرية" },
  "foul-egg": { text: "إنجليزي ده يا مرسي؟", from: "مدرسة المشاغبين" },
  "foul-omelet": { text: "ثواني ثواني", from: "سمير وشهير وبهير" },
  "foul-baba": { text: "بابا عايز كده", from: "بابا عايز كده" },
  "foul-mesa": { text: "إحنا بتوع الأتوبيس", from: "إحنا بتوع الأتوبيس" },
  "foul-potato": { text: "بطاطس في العيش", from: "أفيهات مصرية" },
  "foul-salad": { text: "خضار يا باشا", from: "أفيهات مصرية" },
  "foul-bastr": { text: "على مسئوليتي", from: "أفلام الأكشن المصرية" },
  "foul-eggpl": { text: "هيه أبويا اتحرق", from: "مدرسة المشاغبين" },
  "foul-special": { text: "أنا الأصل والباقي تقليد", from: "إسماعيل ياسين" },
  "foul-salsa": { text: "يا نهار أسود", from: "عادل إمام" },
  "foul-ghee": { text: "سمنة بلدي يا عم", from: "أفيهات السينما" },
  "foul-meat": { text: "عايز كباب", from: "الإرهاب والكباب" },
  "foul-tahina": { text: "كده يا شيخ", from: "اللمبي" },

  "tam-plain": { text: "اديني عقلك", from: "اللمبي" },
  "tam-stuffed": { text: "محشية من جوه", from: "أفيهات مصرية" },
  "tam-chick": { text: "عين كتكوت", from: "أفيهات مصرية" },
  "tam-omelet": { text: "يا خبر أبيض", from: "عادل إمام" },
  "tam-egg": { text: "آسف على الإزعاج", from: "آسف على الإزعاج" },
  "tam-pickled-eggpl": { text: "مخلل ولا إيه", from: "أفيهات مصرية" },
  "tam-baba": { text: "يا عم الحج", from: "اللمبي / الكبير أوي" },
  "tam-white": { text: "جبنة بيضا ناصعة", from: "أفيهات مصرية" },
  "tam-old": { text: "قديمة بس تِرِند", from: "أفيهات مصرية" },
  "tam-roumi": { text: "رومي يحب الرومي", from: "أفيهات مصرية" },
  "tam-ched": { text: "شيدر يا سيدي", from: "أفيهات مصرية" },
  "tam-mozz": { text: "يا سلام", from: "إسماعيل ياسين" },
  "tam-mix": { text: "مكس على مكس", from: "أفيهات مصرية" },
  "tam-sug": { text: "سجق في الطعمية", from: "أفيهات مصرية" },
  "tam-bastr": { text: "هتخش النار يا جدع", from: "اللمبي" },
  "tam-lemon": { text: "لمونة في الفاكهة", from: "أفيهات مصرية" },
  "tam-spicy": { text: "مشطشطة بالهريسة", from: "أفيهات مصرية" },
  "tam-kiri": { text: "يا واد يا حلو", from: "كلاسيك السينما" },
  "tam-saus": { text: "سوسيس داخل البيت", from: "أفيهات مصرية" },
  "tam-fried-mix": { text: "مقليات على بعض", from: "أفيهات مصرية" },
  "tam-eggpl": { text: "باذنجان مقلي وسلام", from: "أفيهات مصرية" },
  "tam-special": { text: "مخصوص أوي", from: "أفيهات مصرية" },
  "tam-fingers": { text: "أقف؟ أقف", from: "مدرسة المشاغبين" },
  "tam-chips": { text: "يا primitive", from: "تيمور وشفيقة" },

  "ori-mesa": { text: "مسقعة الزمان", from: "أفيهات مصرية" },
  "ori-baba": { text: "غنوج ولا غنّوج", from: "أفيهات مصرية" },
  "ori-eggpl": { text: "مقلي ومش ندمان", from: "أفيهات مصرية" },
  "ori-old": { text: "جبنة زمان", from: "أفيهات مصرية" },
  "ori-white": { text: "بيضا زي القمر", from: "أفيهات مصرية" },
  "ori-tomato": { text: "سلام يا صاحبي", from: "سلام يا صاحبي" },
  "ori-fries": { text: "محمرة ومكرمشة", from: "أفيهات مصرية" },
  "ori-pomme": { text: "بوم فريت يا فندم", from: "أفيهات مصرية" },
  "ori-chips": { text: "شيبسي الساعة 8", from: "أفيهات مصرية" },
  "ori-mash": { text: "المزريطة", from: "الكبير أوي" },
  "ori-mash-egg": { text: "بيوري وبيضة", from: "أفيهات مصرية" },
  "ori-mash-omelet": { text: "مقلي على مهروس", from: "أفيهات مصرية" },
  "ori-mash-bastr": { text: "بسطرمة في البيوري", from: "أفيهات مصرية" },
  "ori-pomme-roumi": { text: "رومي على بطاطس", from: "أفيهات مصرية" },
  "ori-dynamite": { text: "ديناميت الصبح", from: "أفيهات مصرية" },
  "ori-shak": { text: "عسل أسود", from: "عسل أسود" },
  "ori-thyme": { text: "زعتر وزيتون", from: "أفيهات مصرية" },

  "om-plain": { text: "سادة ومش سادة", from: "أفيهات مصرية" },
  "om-bastr": { text: "طيور الظلام", from: "طيور الظلام" },
  "om-sug": { text: "سجق الصباح", from: "أفيهات مصرية" },
  "om-pizza": { text: "بيتزا الفطار", from: "أفيهات مصرية" },
  "om-kiri": { text: "كيري في العيش", from: "أفيهات مصرية" },
  "om-roumi": { text: "مرجان أحمد مرجان", from: "مرجان أحمد مرجان" },
  "om-ched": { text: "عمارة يعقوبيان", from: "عمارة يعقوبيان" },
  "om-mozz": { text: "موتزا الصبح", from: "أفيهات مصرية" },
  "om-mix": { text: "مكس الجبن يا سيدي", from: "أفيهات مصرية" },
  "om-boiled": { text: "بعد 14 سنة خدمة", from: "مدرسة المشاغبين" },
  "om-roll": { text: "دحروجة في الزبدة", from: "أفيهات مصرية" },
  "om-veg": { text: "خضار في البيض", from: "أفيهات مصرية" },
  "om-saus": { text: "حسن ومرقص", from: "حسن ومرقص" },

  "green-plain": { text: "أخضر من بره", from: "أفيهات مصرية" },
  "green-stuffed": { text: "جرين ومحشية", from: "أفيهات مصرية" },
  "green-bastr": { text: "بسطرمة خضرا", from: "أفيهات مصرية" },
  "green-mix": { text: "جرين مكس", from: "أفيهات مصرية" },
  "green-kiri": { text: "كيري أخضر", from: "أفيهات مصرية" },
  "green-egg": { text: "بيض في الجرين", from: "أفيهات مصرية" },
  "green-egg-cheese": { text: "بيض وجبنة تمام", from: "أفيهات مصرية" },

  "fr-plain": { text: "الكبير أوي", from: "الكبير أوي" },
  "fr-ketch": { text: "كاتشب على البطاطس", from: "أفيهات مصرية" },
  "fr-mayo": { text: "معلش يا باشا", from: "عادل إمام" },
  "fr-ketch-mayo": { text: "الاتنين أحسن", from: "أفيهات مصرية" },
  "fr-egg": { text: "أنا ما شفتش حاجة", from: "شاهد ما شافش حاجة" },
  "fr-omelet": { text: "سيبها على الله", from: "أفلام مصرية" },
  "fr-white": { text: "جبنة على بوم فريت", from: "أفيهات مصرية" },
  "fr-roumi": { text: "الواد سيد الشغال", from: "الواد سيد الشغال" },
  "fr-ched": { text: "حاضر يا بيه", from: "الواد سيد الشغال" },
  "fr-mozz": { text: "موتزا بتتمدد", from: "أفيهات مصرية" },
  "fr-mix": { text: "من الآخر كده", from: "أفيهات مصرية" },
  "fr-feta": { text: "فيتا الصبح", from: "أفيهات مصرية" },
  "fr-qarish": { text: "قريش يا قريش", from: "أفيهات مصرية" },
  "fr-baba": { text: "غنوج على بطاطس", from: "أفيهات مصرية" },
  "fr-eggpl": { text: "باذنجان فوق الفريت", from: "أفيهات مصرية" },
  "fr-pickled-eggpl": { text: "مخلل فوق البطاطس", from: "أفيهات مصرية" },
  "fr-saus": { text: "سوسيس فاخر", from: "أفيهات مصرية" },
  "fr-bazooka": { text: "بازوكا الفطار", from: "أفيهات مصرية" },
  "fr-chips": { text: "جوني جوني", from: "الكبير أوي" },
  "fr-mash": { text: "مهروسة وتمام", from: "أفيهات مصرية" },
  "fr-panne": { text: "يا عم أنا صعيدي", from: "صعيدي في الجامعة الأمريكية" },
  "fr-mash-butter": { text: "زبدة في المهروسة", from: "أفيهات مصرية" },
  "fr-mash-egg": { text: "بيضة على بيوري", from: "أفيهات مصرية" },
  "fr-mash-omelet": { text: "أومليت على بيوري", from: "أفيهات مصرية" },
  "fr-mash-bastr": { text: "بسطرمة على بيوري", from: "أفيهات مصرية" },
  "fr-chips-ketch": { text: "شيبسي كاتشب", from: "أفيهات مصرية" },
  "fr-chips-mayo": { text: "شيبسي مايونيز", from: "أفيهات مصرية" },
  "fr-chips-mix": { text: "شيبسي الاتنين", from: "أفيهات مصرية" },
  "fr-panne-mix": { text: "بانيه بالصوص", from: "أفيهات مصرية" },

  "meat-liver": { text: "كبدة ولا كبدة", from: "أفيهات مصرية" },
  "meat-sug": { text: "سجق العزومة", from: "أفيهات مصرية" },
  "meat-burger": { text: "برجر سادة جدع", from: "أفيهات مصرية" },
  "meat-burger-egg": { text: "برجر وبيضة", from: "أفيهات مصرية" },
  "meat-burger-cheese": { text: "برجر جبنة خلاص", from: "أفيهات مصرية" },
  "meat-burger-mix": { text: "ميكس على ميكس", from: "أفيهات مصرية" },
  "meat-hawawshi": { text: "حواوشي المكتب", from: "أفيهات مصرية" },

  "roll-foul": { text: "صواريخ ف.م", from: "أفيهات مصرية" },
  "roll-tam": { text: "صواريخ طعمية", from: "أفيهات مصرية" },
  "roll-potato": { text: "رول البطاطس طلع", from: "أفيهات مصرية" },
  "roll-mix": { text: "رول مكس الجبن", from: "أفيهات مصرية" },
  "roll-mozz": { text: "رول بيمط", from: "أفيهات مصرية" },
  "roll-pepper": { text: "فلفل في الرول", from: "أفيهات مصرية" },
  "roll-saus": { text: "رول سوسيس نار", from: "أفيهات مصرية" },
  "roll-bastr": { text: "رول بسطرمة يا عم", from: "أفيهات مصرية" },
  "roll-sug": { text: "رول سجق تقيل", from: "أفيهات مصرية" },
  "roll-om-mix": { text: "رول أومليت مكس", from: "أفيهات مصرية" },
  "roll-falafel-mix": { text: "فلافل في الرول", from: "أفيهات مصرية" },
  "roll-shabrawy": { text: "رول البيت", from: "أفيهات مصرية" },
  "roll-om-saus": { text: "أومليت وسوسيس رول", from: "أفيهات مصرية" },
  "roll-liver": { text: "رول كبدة يا سيدي", from: "أفيهات مصرية" },

  "app-lemon": { text: "لمون معصفر جاهز", from: "أفيهات مصرية" },
  "app-olives": { text: "زيتون الصباح", from: "أفيهات مصرية" },
  "app-cucumber": { text: "خيار مخلل ظريف", from: "أفيهات مصرية" },
  "app-mix-pickle": { text: "مشكل الطرشي", from: "أفيهات مصرية" },
  "app-tomato": { text: "طماطم مخلل", from: "أفيهات مصرية" },
  "app-eggpl-pick": { text: "باذنجان مخلل", from: "أفيهات مصرية" },
  "app-eggpl-fried": { text: "علبة بيتنجان", from: "أفيهات مصرية" },
  "app-salad": { text: "سلطة بلدي نضيفة", from: "أفيهات مصرية" },
  "app-tahini": { text: "طحينة على الوش", from: "أفيهات مصرية" },
  "app-pickles-plate": { text: "طبق طرشي كامل", from: "أفيهات مصرية" },
  "app-omelet": { text: "علبة أومليت", from: "أفيهات مصرية" },
  "app-pepper": { text: "فلفل مقلي حار", from: "أفيهات مصرية" },
  "app-toum": { text: "ثومية تخلي الدنيا", from: "أفيهات مصرية" },

  "misc-disc": { text: "قرص زيادة", from: "أفيهات مصرية" },
  "misc-disc-stuffed": { text: "قرص محشي", from: "أفيهات مصرية" },
  "misc-disc-chick": { text: "قرص عين كتكوت", from: "أفيهات مصرية" },
  "misc-fries-pack": { text: "باكيت الفريت", from: "أفيهات مصرية" },
  "misc-egg": { text: "بيضة مسلوقة وخلاص", from: "أفيهات مصرية" },
  "misc-shami-loaf": { text: "رغيف شامي زيادة", from: "أفيهات مصرية" },
  "misc-balady-loaf": { text: "رغيف بلدي الأصل", from: "أفيهات مصرية" },
  "misc-disc-roumi": { text: "قرص رومي", from: "أفيهات مصرية" },
  "misc-disc-ched": { text: "قرص شيدر", from: "أفيهات مصرية" },
  "misc-disc-mozz": { text: "قرص موتزا", from: "أفيهات مصرية" },
  "misc-disc-mix": { text: "قرص مكس", from: "أفيهات مصرية" },
  "misc-eggpl": { text: "باذنجان على طول", from: "أفيهات مصرية" },
  "misc-baba": { text: "غنوج سادة", from: "أفيهات مصرية" },
  "misc-tomato": { text: "طماطم في النص", from: "أفيهات مصرية" },
  "misc-french": { text: "فرنساوي الصعيد", from: "أفيهات مصرية" },
  "misc-mesa": { text: "مسقعة لوحدها", from: "أفيهات مصرية" },
  "misc-mesa-mt": { text: "لصوص لكن ظرفاء", from: "لصوص لكن ظرفاء" },
  "misc-mesa-sg": { text: "المشبوه", from: "المشبوه" },
  "misc-shak": { text: "شكشوكة Beladi", from: "أفيهات مصرية" },
  "misc-egga": { text: "عجة البيت", from: "أفيهات مصرية" },
  "misc-fried": { text: "الأفوكاتو", from: "الأفوكاتو" },

  "plt-plain": { text: "طبق سادة وكفاية", from: "أفيهات مصرية" },
  "plt-special": { text: "طبق استبيشال", from: "أفيهات مصرية" },
  "plt-bastr": { text: "طبق بسطرمة", from: "أفيهات مصرية" },
  "plt-sug": { text: "طبق سجق", from: "أفيهات مصرية" },
  "plt-pizza": { text: "طبق بيتزا بيض", from: "أفيهات مصرية" },
  "plt-roumi": { text: "طبق رومي", from: "أفيهات مصرية" },
  "plt-ched": { text: "طبق شيدر", from: "أفيهات مصرية" },
  "plt-mozz": { text: "طبق موتزا", from: "أفيهات مصرية" },
  "plt-mix": { text: "طبق مكس الجبن", from: "أفيهات مصرية" },

  "box-plain": { text: "علبة فول سادة", from: "أفيهات مصرية" },
  "box-alex": { text: "علبة إسكندراني", from: "أفيهات مصرية" },
  "box-olive": { text: "زيت زيتون في العلبة", from: "أفيهات مصرية" },
  "box-sug": { text: "علبة سجق فول", from: "أفيهات مصرية" },
  "box-mesa": { text: "علبة مسقعة", from: "أفيهات مصرية" },
  "box-baba": { text: "علبة غنوج", from: "أفيهات مصرية" },
  "box-old": { text: "علبة جبنة قديمة", from: "أفيهات مصرية" },
  "box-toum": { text: "علبة تومية", from: "أفيهات مصرية" },
  "box-taameya": { text: "عجينة الطعمية", from: "أفيهات مصرية" },
  "box-hotoil": { text: "زيت حار في علبة", from: "أفيهات مصرية" },
  "box-lemon": { text: "فول بلمون في علبة", from: "أفيهات مصرية" },
  "box-bastr": { text: "علبة بسطرمة", from: "أفيهات مصرية" },
  "box-butter": { text: "علبة زبدة", from: "أفيهات مصرية" },
  "box-mash": { text: "علبة بيوري", from: "أفيهات مصرية" },
  "box-mash-bastr": { text: "علبة بيوري بسطرمة", from: "أفيهات مصرية" },
  "box-feta": { text: "علبة فيتا", from: "أفيهات مصرية" },
  "box-thyme": { text: "علبة زعتر", from: "أفيهات مصرية" },
  "box-mahmoug": { text: "اللمبي 8 جيجا", from: "اللمبي 8 جيجا" },
  "box-ghee": { text: "أكل العيش يا معلم", from: "أفيهات السينما" },
  "box-meat": { text: "الإرهاب والكباب", from: "الإرهاب والكباب" },
  "box-tahina": { text: "علبة طحينة", from: "أفيهات مصرية" },
  "box-tesha": { text: "تِشة يا عم", from: "أفيهات مصرية" },
  "box-shak": { text: "علبة شكشوكة", from: "أفيهات مصرية" },
  "box-mesa-mt": { text: "علبة مسقعة لحمة", from: "أفيهات مصرية" },
  "box-mesa-sg": { text: "علبة مسقعة سجق", from: "أفيهات مصرية" },
  "box-mesa-so": { text: "علبة مسقعة سوسيس", from: "أفيهات مصرية" },
  "box-corn": { text: "ذرة في العلبة", from: "أفيهات مصرية" },
  "box-sausage": { text: "علبة سوسيس", from: "أفيهات مصرية" },
  "box-batpur": { text: "علبة بطاطس مهروسة", from: "أفيهات مصرية" },

  "egg-roll": { text: "بيض ملفوف", from: "أفيهات مصرية" },
  "egg-boiled": { text: "مسلوق ومش ندمان", from: "أفيهات مصرية" },
  "egg-omelet": { text: "أومليت المكتب", from: "أفيهات مصرية" },
  "egg-bastr": { text: "بيض بسطرمة", from: "أفيهات مصرية" },
  "egg-roumi": { text: "بيض رومي", from: "أفيهات مصرية" },
  "egg-ched": { text: "بيض شيدر", from: "أفيهات مصرية" },
  "egg-saus": { text: "بيض سوسيس", from: "أفيهات مصرية" },
  "egg-chez-tom": { text: "واحدة بواحدة", from: "واحدة بواحدة" },

  "bat-fingers": { text: "أصابع البطاطس", from: "أفيهات مصرية" },
  "bat-chips": { text: "شيبسي البيت", from: "أفيهات مصرية" },
  "bat-puree": { text: "بيوري سادة", from: "أفيهات مصرية" },
  "bat-panne": { text: "بانيه الفطار", from: "أفيهات مصرية" },
  "bat-ketch": { text: "كاتشب زيادة", from: "أفيهات مصرية" },
  "bat-mayo": { text: "مايونيز زيادة", from: "أفيهات مصرية" },
  "bat-mix": { text: "بطاطس مكس", from: "أفيهات مصرية" },
  "bat-ched": { text: "بطاطس شيدر", from: "أفيهات مصرية" },
  "bat-roumi": { text: "بطاطس رومي", from: "أفيهات مصرية" },
  "bat-boiled": { text: "بطاطس وبيضة", from: "أفيهات مصرية" },
  "bat-omelet": { text: "بطاطس وأومليت", from: "أفيهات مصرية" },
  "bat-shrimp": { text: "السفارة في العمارة", from: "السفارة في العمارة" },
};

function hash(s) {
  let h = 0;
  for (const c of String(s)) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return h;
}

export function afeya(id) {
  if (AFEYAT[id]) return AFEYAT[id];
  return POOL[hash(id) % POOL.length];
}
