export const ink = "#2b2320", cream = "#fbf6ec", paper = "#fffdf8",
  clay = "#c0392b", clayDark = "#9c2a1e", line = "#e7ddcb",
  muted = "#8a7f70", yolk = "#f2b134", green = "#2f6b4f";

export const globalCss = `
  html,body,#root{min-height:100%;width:100%;max-width:100%;overflow-x:clip;}
  *{box-sizing:border-box;-webkit-tap-highlight-color:transparent;}
  @keyframes spin{to{transform:rotate(360deg);}}
  .spin{animation:spin .9s linear infinite;}
  @keyframes floaty{0%,100%{transform:translateY(0);}50%{transform:translateY(-6px);}}
  @keyframes rise{from{opacity:0;transform:translate(-50%,12px);}to{opacity:1;transform:translate(-50%,0);}}
  button:focus-visible{outline:2px solid ${clay};outline-offset:2px;}
  input:focus-visible{outline:2px solid ${clay};outline-offset:1px;}
  @keyframes bravoPop{0%{transform:scale(.45) rotate(-10deg);opacity:0;}55%{transform:scale(1.1) rotate(3deg);opacity:1;}100%{transform:scale(1) rotate(0);}}
  .bravo-pop{animation:bravoPop .38s cubic-bezier(.2,1.4,.4,1);}
  @keyframes haramShake{0%,100%{transform:rotate(0) scale(1);}18%{transform:rotate(-5deg) scale(1.08);}36%{transform:rotate(5deg) scale(1.06);}54%{transform:rotate(-4deg) scale(1.04);}72%{transform:rotate(3deg);} }
  .haram-pop{animation:haramShake .5s ease;}
  @keyframes shopGlow{0%,100%{box-shadow:0 0 0 3px rgba(255,90,31,.22);}50%{box-shadow:0 0 0 7px rgba(255,90,31,.08);}}
  .chip-shop{animation:shopGlow 1.7s ease-in-out infinite;}
  @media (prefers-reduced-motion:reduce){.spin,[style*="floaty"],.bravo-pop,.haram-pop,.chip-shop{animation:none!important;}}
  ::-webkit-scrollbar{height:7px;width:7px;}::-webkit-scrollbar-thumb{background:${line};border-radius:9px;}
  .catRail::-webkit-scrollbar{display:none;}
  .catRail{scrollbar-width:none;-webkit-overflow-scrolling:touch;}
  @media (max-height: 700px){.pay-qr{max-width:140px!important;margin-top:4px!important;margin-bottom:4px!important;}}
  .auth-logo{width:100%!important;max-width:100%;height:auto;margin:0 auto 8px!important;}
  @media (max-height: 620px){.auth-logo{max-height:150px;object-fit:contain;}}
`;

export const S = {
  app: { fontFamily: "'DM Sans',ui-sans-serif,system-ui,sans-serif", background: cream, color: ink, minHeight: "100dvh" },
  screenCenter: { fontFamily: "'Cairo','DM Sans',ui-sans-serif,system-ui,sans-serif", minHeight: "100dvh", width: "100%", maxWidth: "100%", boxSizing: "border-box", background: "#F4F4F4", color: ink, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 0, padding: "16px 14px calc(20px + env(safe-area-inset-bottom))", overflowY: "auto", overflowX: "hidden" },
  authStack: { width: "min(430px, 100%)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 0 },
  loadPulse: { color: clay, animation: "floaty 2.2s ease-in-out infinite" },
  loadText: { color: muted, fontSize: 15, textAlign: "center", fontFamily: "'Cairo','DM Sans',sans-serif" },

  signCard: { background: "#fff", border: "none", borderRadius: 28, padding: "18px 18px 22px", width: "100%", minWidth: 0, boxSizing: "border-box", boxShadow: "0 16px 40px -24px rgba(0,0,0,.28)", display: "flex", flexDirection: "column", alignItems: "stretch" },
  brandRow: { display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center", gap: 8, marginBottom: 16 },
  logoXl: { width: "100%", maxWidth: 420, height: "auto", display: "block", objectFit: "contain", background: "transparent", border: "none", margin: "0 auto 4px" },
  logoLg: { width: "min(220px, 64vw)", height: "auto", display: "block", objectFit: "contain", background: "transparent", border: "none", margin: "0 auto 4px" },
  authTagline: { margin: "0 8px 18px", fontSize: 14, lineHeight: 1.55, color: muted, textAlign: "center", fontFamily: "'Cairo','DM Sans',sans-serif", fontWeight: 700 },
  logoSm: { width: 108, height: "auto", display: "block", objectFit: "contain", background: "transparent", border: "none", flexShrink: 0 },
  logoAvatar: { width: 42, height: 42, borderRadius: "50%", objectFit: "cover", display: "block", background: "#eee", flexShrink: 0 },
  logoLock: { width: 58, height: "auto", display: "block", objectFit: "contain", background: "transparent", border: "none", flexShrink: 0 },
  brandTitle: { fontFamily: "'Cairo','Fraunces',Georgia,serif", fontSize: 22, fontWeight: 700, margin: 0, letterSpacing: 0, lineHeight: 1.35 },
  brandSub: { margin: "3px 0 0", fontSize: 13.5, color: muted, fontFamily: "'Cairo','DM Sans',sans-serif" },
  label: { display: "block", fontSize: 13, fontWeight: 700, color: muted, marginBottom: 7, fontFamily: "'Cairo','DM Sans',sans-serif" },
  input: { width: "100%", padding: "13px 15px", fontSize: 16, borderRadius: 12, border: `1.5px solid ${line}`, background: cream, color: ink, fontFamily: "inherit" },
  select: { width: "100%", padding: "13px 15px", fontSize: 16, borderRadius: 12, border: `1.5px solid ${line}`, background: cream, color: ink, fontFamily: "'Cairo','DM Sans',sans-serif", cursor: "pointer" },
  choiceGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  choiceChip: { background: cream, border: `1.5px solid ${line}`, color: ink, borderRadius: 12, padding: "11px 8px", fontSize: 13, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif", textAlign: "center", lineHeight: 1.3 },
  choiceChipOn: { background: ink, color: cream, borderColor: ink },
  inboxBanner: { display: "block", width: "calc(100% - 36px)", margin: "0 18px 14px", background: ink, color: cream, border: "none", borderRadius: 16, padding: "12px 14px", fontSize: 14, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif", textAlign: "right" },
  errText: { color: clay, fontSize: 13, marginTop: 10, fontWeight: 600 },
  okText: { color: green, fontSize: 13, marginTop: 10, fontWeight: 600 },
  finePrint: { fontSize: 12.5, color: muted, marginTop: 14, lineHeight: 1.5 },
  linkBtn: { background: "none", border: "none", color: clay, fontWeight: 700, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif", fontSize: 13.5, padding: 0, marginTop: 14, width: "100%", textAlign: "center" },
  signupHint: { marginTop: 16, display: "flex", flexDirection: "column", alignItems: "center", gap: 8, textAlign: "center", fontSize: 14, color: muted, fontFamily: "'Cairo','DM Sans',sans-serif" },
  signupLink: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: "100%", background: yolk, color: ink, border: "none", borderRadius: 14, padding: "12px 14px", fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif", fontSize: 15 },
  authMemeCard: { background: paper, borderRadius: 20, padding: "12px 12px 16px", width: "min(420px, 92vw)", maxHeight: "min(92dvh, 640px)", overflowY: "auto", textAlign: "center", boxShadow: "0 24px 60px -18px rgba(0,0,0,.5)", cursor: "default" },
  authMemeCap: { margin: "10px 8px 12px", fontFamily: "'Cairo','DM Sans',sans-serif", fontWeight: 800, fontSize: 18, lineHeight: 1.45, color: ink },

  header: { position: "sticky", top: 0, zIndex: 20, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 12px", background: "rgba(251,246,236,.92)", backdropFilter: "blur(8px)", borderBottom: `1px solid ${line}`, flexWrap: "wrap", gap: 8 },
  hello: { fontSize: 13, color: muted, marginRight: 2, maxWidth: "min(100%, 14em)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  brandRowSm: { display: "flex", gap: 12, alignItems: "center" },
  headerTitle: { fontFamily: "'Cairo','Fraunces',Georgia,serif", fontSize: 18, fontWeight: 800, letterSpacing: 0, lineHeight: 1.25, maxWidth: "14em" },
  headerRight: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", maxWidth: "100%" },

  ghostBtn: { display: "inline-flex", alignItems: "center", gap: 6, background: "transparent", border: `1.5px solid ${line}`, color: ink, borderRadius: 10, padding: "8px 12px", fontSize: 13.5, fontWeight: 600, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif" },
  primaryBtn: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, background: clay, color: "#fff", border: "none", borderRadius: 12, padding: "12px 18px", fontSize: 15, fontWeight: 700, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif", boxShadow: `0 8px 20px -12px ${clayDark}` },

  shopWrap: { maxWidth: 1080, margin: "0 auto", padding: "14px 12px calc(28px + env(safe-area-inset-bottom))" },
  dateBanner: { display: "flex", flexDirection: "column", gap: 2, padding: "16px 20px", background: paper, border: `1px solid ${line}`, borderRadius: 16, marginBottom: 16, borderLeft: `5px solid ${yolk}` },
  dateEyebrow: { fontSize: 12.5, fontWeight: 700, letterSpacing: 0, textTransform: "none", color: clay, fontFamily: "'Cairo','DM Sans',sans-serif" },
  dateBig: { fontFamily: "'Fraunces',Georgia,serif", fontSize: 21, fontWeight: 600, letterSpacing: "-.01em" },

  tabRow: { display: "flex", gap: 8, marginBottom: 16 },
  tabBtn: { background: "transparent", border: `1.5px solid ${line}`, color: muted, borderRadius: 999, padding: "8px 16px", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif" },
  tabActive: { background: ink, color: cream, borderColor: ink },

  columns: { display: "grid", gridTemplateColumns: "minmax(0,1fr) 340px", gap: 20, alignItems: "start" },
  menuCol: { minWidth: 0 },
  catTabs: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 8, marginBottom: 14 },
  catTab: { flexShrink: 0, background: paper, border: `1.5px solid ${line}`, borderRadius: 10, padding: "8px 13px", cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif", color: ink, fontWeight: 700, fontSize: 13.5 },
  catTabHot: { borderColor: yolk, background: "#fff8dc", color: ink },
  catTabActive: { borderColor: clay, background: "#fdeee3", color: clayDark },

  menuGrid: { display: "grid", gap: 10 },
  menuCard: { display: "flex", alignItems: "center", gap: 12, width: "100%", textAlign: "right", background: paper, border: `1px solid ${line}`, borderRadius: 14, padding: 10, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif", color: ink },
  memeFrame: { width: 84, height: 84, flexShrink: 0, position: "relative" },
  menuImg: { width: 84, height: 84, borderRadius: 12, objectFit: "cover", background: cream, border: `1px solid ${line}`, display: "block" },
  memeBar: { position: "absolute", left: 1, right: 1, bottom: 1, background: "rgba(43,35,32,.88)", color: cream, fontFamily: "'Cairo','Segoe UI',sans-serif", fontSize: 10, fontWeight: 700, textAlign: "center", padding: "5px 4px", borderRadius: "0 0 11px 11px", lineHeight: 1.25 },
  menuQtyBadge: { position: "absolute", top: -6, left: -6, minWidth: 22, height: 22, padding: "0 6px", borderRadius: 999, background: clay, color: "#fff", fontSize: 12, fontWeight: 800, display: "grid", placeItems: "center" },
  menuBody: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 2 },
  afeyaFrom: { fontSize: 11, color: muted, fontFamily: "'Cairo','Segoe UI',sans-serif", marginBottom: 4 },
  cartThumb: { width: 40, height: 40, borderRadius: 8, objectFit: "cover", flexShrink: 0, background: cream },
  menuTop: { display: "flex", justifyContent: "space-between", gap: 8, alignItems: "baseline", width: "100%" },
  menuName: { fontWeight: 800, fontSize: 16, lineHeight: 1.3 },
  menuAr: { fontSize: 11.5, color: muted, fontFamily: "'Cairo','Segoe UI',sans-serif" },
  menuHint: { fontSize: 12.5, fontWeight: 700, color: clayDark, display: "inline-flex", alignItems: "center", gap: 4 },
  menuPriceHint: { fontSize: 13, fontWeight: 700, color: muted, marginTop: 2 },
  pickCard: { background: paper, borderRadius: 20, padding: "18px 16px 16px", width: "min(420px, 94vw)", textAlign: "right", boxShadow: "0 24px 60px -18px rgba(0,0,0,.5)", cursor: "default" },
  pickHead: { display: "flex", alignItems: "center", gap: 12, marginBottom: 14 },
  pickThumb: { width: 64, height: 64, borderRadius: 12, objectFit: "cover", flexShrink: 0, background: cream, border: `1px solid ${line}` },
  pickList: { display: "grid", gap: 8 },
  pickRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, background: cream, border: `1.5px solid ${line}`, borderRadius: 12, padding: "12px 12px" },
  pickRowName: { fontSize: 15, fontWeight: 800, fontFamily: "'Cairo',sans-serif", marginBottom: 2 },
  tierRow: { display: "grid", gap: 6, alignItems: "stretch" },
  tierChip: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 3, background: cream, border: `1.5px solid ${line}`, borderRadius: 10, padding: "7px 4px 6px", minWidth: 0 },
  tierChipSingle: { display: "flex", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10, background: cream, border: `1.5px solid ${line}`, borderRadius: 10, padding: "8px 10px" },
  tierChipActive: { borderColor: clay, background: "#fdeee3" },
  tierName: { fontSize: 11.5, fontWeight: 800, color: ink },
  tierPrice: { fontSize: 13.5, fontWeight: 800, color: clay, fontFamily: "'Cairo','DM Sans',sans-serif" },
  tierAdd: { width: 26, height: 26, borderRadius: 8, background: ink, color: cream, border: "none", display: "grid", placeItems: "center", cursor: "pointer" },
  tierStepper: { display: "flex", alignItems: "center", gap: 3 },
  stepBtnXs: { width: 24, height: 24, borderRadius: 7, border: `1.5px solid ${line}`, background: paper, color: ink, display: "grid", placeItems: "center", cursor: "pointer" },
  stepQtyXs: { minWidth: 16, textAlign: "center", fontWeight: 700, fontSize: 13 },

  stepperSm: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0 },
  stepBtn: { width: 28, height: 28, borderRadius: 8, border: `1.5px solid ${line}`, background: cream, color: ink, display: "grid", placeItems: "center", cursor: "pointer" },
  stepQty: { minWidth: 18, textAlign: "center", fontWeight: 700, fontSize: 14 },

  tierTag: { display: "inline-block", fontSize: 11, fontWeight: 700, color: clayDark, background: "#fdeee3", borderRadius: 6, padding: "1px 6px", marginLeft: 4, verticalAlign: "middle" },

  myOrderBox: { background: "#f3f8f2", border: "1px solid #cfe4d0", borderRadius: 14, padding: "16px 18px" },
  myOrderHead: { display: "flex", alignItems: "center", gap: 7, fontWeight: 700, color: green, marginBottom: 10 },
  myOrderLine: { display: "flex", justifyContent: "space-between", gap: 10, fontSize: 14, padding: "3px 0", color: ink },
  myOrderTotal: { display: "flex", justifyContent: "space-between", fontWeight: 700, borderTop: "1px dashed #cfe4d0", marginTop: 8, paddingTop: 8 },
  billRow: { display: "flex", justifyContent: "space-between", gap: 10, fontSize: 13.5, color: muted, padding: "3px 0", fontFamily: "'Cairo','DM Sans',sans-serif" },
  billGrand: { display: "flex", justifyContent: "space-between", gap: 10, fontWeight: 800, borderTop: `1px dashed ${line}`, marginTop: 6, paddingTop: 8, marginBottom: 4, fontSize: 15.5, fontFamily: "'Cairo','DM Sans',sans-serif" },

  cartCol: { position: "sticky", top: 74 },
  cartCard: { background: paper, border: `1px solid ${line}`, borderRadius: 16, padding: "18px 18px 20px", boxShadow: "0 14px 40px -30px rgba(80,50,20,.5)" },
  cartHead: { display: "flex", alignItems: "center", gap: 9, fontWeight: 700, fontSize: 16, marginBottom: 14 },
  cartBadge: { marginLeft: "auto", background: clay, color: "#fff", borderRadius: 999, fontSize: 12.5, fontWeight: 700, padding: "2px 9px" },
  cartEmpty: { color: muted, fontSize: 14, lineHeight: 1.5, margin: 0 },
  cartLines: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 14 },
  cartLine: { display: "flex", alignItems: "center", gap: 8 },
  cartLineName: { fontSize: 14, fontWeight: 600, fontFamily: "'Cairo','DM Sans',sans-serif" },
  cartLineMeta: { fontSize: 12, color: muted },
  trashBtn: { background: "transparent", border: "none", color: muted, cursor: "pointer", padding: 4, display: "grid", placeItems: "center" },
  cartTotalRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", padding: "12px 0", borderTop: `1px solid ${line}`, marginBottom: 12, fontWeight: 700 },
  cartTotalNum: { fontFamily: "'Fraunces',Georgia,serif", fontSize: 20, color: clay },

  historyWrap: { display: "grid", gap: 12, maxWidth: 640 },

  toast: { position: "fixed", bottom: "calc(88px + env(safe-area-inset-bottom))", left: "50%", transform: "translateX(-50%)", color: "#fff", padding: "12px 20px", borderRadius: 12, fontSize: 14, fontWeight: 600, display: "flex", alignItems: "center", gap: 8, boxShadow: "0 12px 30px -12px rgba(0,0,0,.4)", zIndex: 95, animation: "rise .25s ease", maxWidth: "min(90vw, 420px)" },

  adminWrap: { maxWidth: 1080, margin: "0 auto", padding: "14px 12px calc(28px + env(safe-area-inset-bottom))" },
  adminPad: { maxWidth: 1080, margin: "0 auto", padding: "60px 16px", display: "flex", flexDirection: "column", alignItems: "center", gap: 14 },
  adminTopRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 16, flexWrap: "wrap", gap: 8 },
  adminH: { fontFamily: "'Fraunces',Georgia,serif", fontSize: 24, fontWeight: 600, margin: "2px 0 0", letterSpacing: "-.02em" },
  emptyState: { background: paper, border: `1px dashed ${line}`, borderRadius: 16, padding: "40px 24px", textAlign: "center" },

  dateTabs: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 6, marginBottom: 14 },
  dateTab: { flexShrink: 0, display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 2, background: paper, border: `1.5px solid ${line}`, borderRadius: 12, padding: "9px 14px", cursor: "pointer", fontFamily: "inherit", color: ink, fontWeight: 700, fontSize: 14 },
  dateTabActive: { borderColor: clay, background: "#fdeee3", color: clayDark },
  dateTabDate: { fontSize: 11, fontWeight: 500, color: muted },

  adminActions: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14, flexWrap: "wrap" },
  runHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, margin: "4px 0 8px", fontFamily: "'Cairo',sans-serif", fontSize: 16, fontWeight: 800 },
  runHeadClosed: { color: muted, marginTop: 18 },
  runCard: { display: "grid", gap: 10, paddingBottom: 10 },
  runActs: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  adminStat: { marginLeft: "auto", fontSize: 14, color: muted, fontWeight: 600 },
  adminStatBar: { display: "flex", flexWrap: "wrap", gap: "8px 14px", background: paper, border: `1px solid ${line}`, borderRadius: 12, padding: "10px 14px", marginBottom: 14, fontSize: 13.5, fontWeight: 700, color: ink, fontFamily: "'Cairo','DM Sans',sans-serif" },
  adminTabs: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 8, marginBottom: 16 },
  adminTab: { display: "flex", flexDirection: "column", alignItems: "center", gap: 4, background: paper, border: `1.5px solid ${line}`, color: muted, borderRadius: 14, padding: "12px 10px", fontSize: 14.5, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo','DM Sans',sans-serif" },
  adminTabActive: { background: ink, color: cream, borderColor: ink },
  adminTabSub: { fontSize: 11, fontWeight: 600, opacity: 0.75 },
  chipRow: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 6, marginBottom: 14 },
  chip: { flexShrink: 0, background: paper, border: `1.5px solid ${line}`, color: ink, borderRadius: 999, padding: "7px 12px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  chipOn: { background: ink, color: cream, borderColor: ink },
  chipShop: { display: "inline-flex", alignItems: "center", gap: 6, flexShrink: 0, background: "#FFF1EA", border: "1.5px solid #FF5A1F", color: "#FF5A1F", borderRadius: 999, padding: "8px 14px", fontSize: 13.5, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif", boxShadow: "0 0 0 3px rgba(255,90,31,.18)" },
  chipShopOn: { background: "#FF5A1F", color: "#fff", borderColor: "#E24A14", boxShadow: "0 8px 18px -8px rgba(255,90,31,.8)" },
  deskNav: { display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  deskNavBtn: { flex: "1 1 140px", background: paper, border: `1.5px solid ${line}`, color: ink, borderRadius: 12, padding: "10px 8px", fontSize: 14, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  deskNavOn: { background: ink, color: cream, borderColor: ink },
  dateBar: { display: "flex", gap: 8, alignItems: "center", marginBottom: 8 },
  dateCal: { flex: 1, display: "flex", alignItems: "center", gap: 8, background: paper, border: `1.5px solid ${line}`, borderRadius: 12, padding: "8px 12px" },
  dateInput: { flex: 1, border: "none", background: "transparent", fontSize: 16, fontFamily: "'Cairo',sans-serif", color: ink, outline: "none" },
  orderList: { display: "grid", gap: 8 },
  orderRow: { background: paper, border: `1px solid ${line}`, borderRadius: 12, overflow: "hidden", boxShadow: `inset -5px 0 0 ${clay}` },
  orderRowPaid: { borderColor: "#b7d9bc", background: "#eef8ef", boxShadow: `inset -5px 0 0 ${green}` },
  orderRowPrice: { fontWeight: 800, color: clay, fontSize: 15, fontFamily: "'Cairo',sans-serif" },
  orderRowPricePaid: { color: green },
  orderRowMain: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, background: "transparent", border: "none", padding: "10px 12px", cursor: "pointer", color: ink, fontFamily: "'Cairo',sans-serif" },
  orderRowMeta: { fontSize: 12, color: muted, fontWeight: 700, marginTop: 2 },
  orderRowHint: { fontSize: 11, color: muted, fontWeight: 700, marginTop: 2 },
  orderRowBody: { padding: "0 12px 10px", borderTop: `1px dashed ${line}` },
  orderRowFoot: { display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "8px 12px", borderTop: `1px solid ${line}` },
  orderRowActs: { display: "flex", flexWrap: "wrap", gap: 6, justifyContent: "flex-end" },
  orderLineActs: { display: "inline-flex", alignItems: "center", gap: 4, flexShrink: 0 },
  orderAddBox: { background: cream, border: `1px dashed ${line}`, borderRadius: 12, padding: 10, margin: "8px 0" },
  orderRowReturned: { borderColor: clay, background: "#fdeee3", boxShadow: `inset -5px 0 0 ${clay}` },
  orderBackStamp: { display: "inline-flex", alignItems: "center", gap: 6, background: clay, color: "#fff", borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 800, fontFamily: "'Cairo',sans-serif" },
  orderClosedStamp: { display: "inline-flex", alignItems: "center", gap: 6, background: ink, color: cream, borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 800, fontFamily: "'Cairo',sans-serif" },
  paidMark: { display: "inline-flex", alignItems: "center", gap: 6, border: "none", background: clay, color: "#fff", borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  pingMark: { display: "inline-flex", alignItems: "center", gap: 6, border: "none", background: "#FF5A1F", color: "#fff", borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  pingMarkOff: { background: "#d9d3c9", color: "#6f675c", cursor: "not-allowed" },
  orderDeliveredStamp: { display: "inline-flex", alignItems: "center", gap: 6, background: "#FF5A1F", color: "#fff", borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 800, fontFamily: "'Cairo',sans-serif" },
  paidStamp: { display: "inline-flex", alignItems: "center", gap: 6, background: green, color: "#fff", borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 800, fontFamily: "'Cairo',sans-serif" },
  paidWait: { fontWeight: 800, color: clay, fontFamily: "'Cairo',sans-serif", fontSize: 13 },
  proofBox: { marginTop: 8, background: cream, border: `1px dashed ${line}`, borderRadius: 12, padding: 10, textAlign: "right" },
  proofImg: { width: "100%", maxWidth: 240, display: "block", margin: "8px auto 0", borderRadius: 10, border: `1px solid ${line}`, background: "#fff" },
  pieGrid: { display: "grid", gap: 12 },
  pieCard: { background: paper, border: `1px solid ${line}`, borderRadius: 16, padding: 16 },
  pieTitle: { fontFamily: "'Cairo',sans-serif", fontSize: 16, fontWeight: 800, margin: "0 0 12px" },
  pieDisc: { width: 150, height: 150, borderRadius: "50%", margin: "0 auto 14px" },
  pieLegend: { listStyle: "none", margin: 0, padding: 0, display: "grid", gap: 8 },
  pieLegendRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13.5, fontWeight: 700, fontFamily: "'Cairo',sans-serif" },
  pieSwatch: { width: 12, height: 12, borderRadius: 4, flexShrink: 0 },
  pieVal: { fontWeight: 800 },
  qrOfficerBox: { background: cream, border: `1px solid ${line}`, borderRadius: 12, padding: 12, marginTop: 8 },
  teamBlock: { background: paper, border: `1px solid ${line}`, borderRadius: 16, padding: "4px 8px", marginBottom: 12, overflow: "hidden" },
  teamHead: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, padding: "10px 6px", margin: 0, border: "none", background: "transparent", cursor: "pointer", color: ink, fontFamily: "'Cairo',sans-serif", textAlign: "right" },
  teamHeadOpen: { borderBottom: `1px solid ${line}`, marginBottom: 10 },
  teamTitle: { fontFamily: "'Cairo',sans-serif", fontWeight: 800, fontSize: 16, margin: 0 },
  teamMeta: { fontSize: 12.5, color: muted, fontWeight: 700, marginTop: 2 },
  userRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, background: paper, border: `1px solid ${line}`, borderRadius: 14, padding: "12px 14px" },
  userCard: { display: "grid", gap: 10, background: paper, border: `1px solid ${line}`, borderRadius: 14, overflow: "hidden" },
  userFold: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, background: "transparent", border: "none", padding: "12px 14px", cursor: "pointer", color: ink, fontFamily: "'Cairo',sans-serif", textAlign: "right" },
  userFoldMeta: { fontSize: 12, color: muted, fontWeight: 700, marginTop: 3, wordBreak: "break-word" },
  userFoldHint: { fontSize: 11, color: muted, fontWeight: 700, marginTop: 2 },
  userBody: { display: "grid", gap: 10, padding: "0 14px 14px", borderTop: `1px dashed ${line}` },
  userActions: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  priceRow: { padding: "12px 0", borderBottom: `1px dashed ${line}` },
  priceRowName: { fontWeight: 800, fontFamily: "'Cairo',sans-serif", fontSize: 15, margin: "0 0 8px" },
  priceFields: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(108px, 1fr))", gap: 8, marginBottom: 8 },
  priceFieldLabel: { display: "block", fontSize: 12, fontWeight: 700, color: muted, marginBottom: 4, fontFamily: "'Cairo',sans-serif" },
  collectorTag: { display: "inline-block", background: cream, border: `1.5px solid ${line}`, color: ink, borderRadius: 999, padding: "3px 10px", fontSize: 12, fontWeight: 800, fontFamily: "'Cairo',sans-serif", marginTop: 6 },
  roleBadge: { display: "inline-block", fontSize: 11, fontWeight: 800, borderRadius: 999, padding: "2px 8px", marginTop: 6, background: cream, color: muted },
  roleBadgeSuper: { background: ink, color: cream },
  roleBadgeAdmin: { background: "#e9f5ea", color: green },
  payFold: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, background: paper, border: `1.5px solid ${line}`, borderRadius: 14, padding: "12px 14px", marginBottom: 10, cursor: "pointer", textAlign: "right", fontFamily: "'Cairo','DM Sans',sans-serif", color: ink },
  payFoldHint: { display: "block", fontSize: 12, fontWeight: 600, color: muted, marginTop: 2 },
  payEditGrid: { display: "grid", gridTemplateColumns: "minmax(140px,180px) minmax(140px,180px) minmax(0,1fr)", gap: 16, alignItems: "start" },
  payEditStack: { display: "grid", gap: 16 },
  payEditTitle: { fontWeight: 800, fontFamily: "'Cairo',sans-serif", marginBottom: 8 },
  qrPreviewSm: { width: "100%", maxWidth: 160, display: "block", margin: "0 auto", borderRadius: 12, background: "#fff", border: `1px solid ${line}` },
  payPhoneLink: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 13, color: clay, marginTop: 4, fontWeight: 700, textDecoration: "none", fontFamily: "'DM Sans',sans-serif" },

  modeRow: { display: "flex", gap: 8, marginBottom: 18, flexWrap: "wrap" },
  modeBtn: { display: "inline-flex", alignItems: "center", gap: 7, background: paper, border: `1.5px solid ${line}`, color: muted, borderRadius: 10, padding: "9px 14px", fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  modeActive: { background: ink, color: cream, borderColor: ink },

  fullWrap: { display: "grid", gap: 14, maxWidth: 720 },
  catBlock: { background: paper, border: `1px solid ${line}`, borderRadius: 14, padding: "14px 16px" },
  catBlockHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline", fontFamily: "'Fraunces',Georgia,serif", fontSize: 16, fontWeight: 600, marginBottom: 8, paddingBottom: 8, borderBottom: `1px solid ${line}` },
  catBlockSub: { fontSize: 14, color: clay },
  tallyLineLight: { display: "flex", alignItems: "center", gap: 10, fontSize: 14.5, padding: "5px 0" },
  tallyQtyDark: { fontFamily: "'Fraunces',Georgia,serif", fontWeight: 600, color: clay, minWidth: 30 },
  personLinePrice: { color: muted, fontSize: 13.5, whiteSpace: "nowrap" },
  grandTotal: { display: "flex", justifyContent: "space-between", background: ink, color: cream, borderRadius: 14, padding: "16px 20px", fontWeight: 700, fontSize: 17, fontFamily: "'Fraunces',Georgia,serif" },

  personGrid: { display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 12, alignItems: "start" },
  payCard: { background: paper, border: `1px solid ${line}`, borderRadius: 14, padding: "14px 16px" },
  payCardPaid: { borderColor: "#cfe4d0", background: "#f6fbf5" },
  payHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 10, marginBottom: 9, paddingBottom: 9, borderBottom: `1px dashed ${line}` },
  personName: { fontWeight: 700, fontSize: 15.5 },
  payPhone: { display: "flex", alignItems: "center", gap: 4, fontSize: 12.5, color: muted, marginTop: 2 },
  payAmount: { fontFamily: "'Fraunces',Georgia,serif", fontWeight: 600, color: clay, fontSize: 18, whiteSpace: "nowrap" },
  personLine: { display: "flex", justifyContent: "space-between", gap: 8, fontSize: 14, padding: "3px 0" },
  payFoot: { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 9, paddingTop: 9, borderTop: `1px solid ${line}` },
  paidToggle: { display: "inline-flex", alignItems: "center", gap: 6, border: `1.5px solid ${line}`, background: cream, borderRadius: 999, padding: "5px 11px", fontSize: 12.5, fontWeight: 700, color: muted, cursor: "pointer", fontFamily: "inherit" },
  paidToggleOn: { borderColor: green, background: "#e9f5ea", color: green },
  personCard: { background: paper, border: `1px solid ${line}`, borderRadius: 14, padding: "14px 16px" },
  personHead: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 8, paddingBottom: 8, borderBottom: `1px dashed ${line}` },
  personTotal: { fontFamily: "'Fraunces',Georgia,serif", fontWeight: 600, color: clay },

  bravoScrim: { position: "fixed", inset: 0, zIndex: 80, background: "rgba(0,0,0,.62)", display: "flex", alignItems: "center", justifyContent: "center", padding: 12, overflowY: "auto", cursor: "pointer", overscrollBehavior: "contain" },
  bravoCard: { position: "relative", maxWidth: "min(420px, 92vw)", margin: "auto" },
  bravoImg: { display: "block", width: "100%", maxHeight: "min(52dvh, 420px)", objectFit: "contain", borderRadius: 18, background: "#111", boxShadow: "0 24px 60px -18px rgba(0,0,0,.7)" },
  bravoYell: { position: "absolute", left: 0, right: 0, bottom: 0, padding: "14px 12px 16px", borderRadius: "0 0 18px 18px", background: "linear-gradient(transparent, rgba(0,0,0,.82))", color: "#ffe14a", fontFamily: "'Cairo','Segoe UI',sans-serif", fontWeight: 800, fontSize: "clamp(22px, 6vw, 34px)", textAlign: "center", lineHeight: 1.2, textShadow: "0 2px 0 #000, 0 0 10px #000", letterSpacing: 0 },
  qrBox: { background: paper, border: `1px solid ${line}`, borderRadius: 16, padding: 16, marginBottom: 16 },
  qrPreview: { width: "100%", maxWidth: 280, display: "block", margin: "10px auto 0", borderRadius: 12, background: "#fff", border: `1px solid ${line}` },
  payScrim: { position: "fixed", inset: 0, zIndex: 80, background: "rgba(0,0,0,.62)", display: "flex", alignItems: "flex-end", justifyContent: "center", padding: 0, overflow: "hidden", cursor: "pointer" },
  payCardModal: { background: paper, borderRadius: "22px 22px 0 0", padding: 0, width: "100%", maxWidth: 430, height: "100dvh", maxHeight: "100dvh", display: "flex", flexDirection: "column", textAlign: "center", boxShadow: "0 -18px 50px -18px rgba(0,0,0,.45)", overflow: "hidden" },
  payModalBody: { flex: 1, minHeight: 0, overflowY: "auto", padding: "14px 16px 10px", WebkitOverflowScrolling: "touch" },
  payModalBar: { flexShrink: 0, padding: "10px 16px calc(14px + env(safe-area-inset-bottom))", borderTop: `1px solid ${line}`, background: paper, textAlign: "center" },
  payQrImg: { width: "100%", maxWidth: 168, height: "auto", objectFit: "contain", borderRadius: 12, background: "#fff", border: `1px solid ${line}`, margin: "8px auto", display: "block" },
  hiddenFile: { display: "none" },
};

export const accent = "#FF5A1F";
export const night = "#1C1C1C";
export const mist = "#F4F4F4";
export const fog = "#8A8A8A";

export const U = {
  app: { fontFamily: "'Cairo','DM Sans',ui-sans-serif,system-ui,sans-serif", background: mist, color: night, minHeight: "100dvh" },
  shell: { maxWidth: 430, margin: "0 auto", minHeight: "100dvh", background: mist, position: "relative", paddingBottom: "calc(96px + env(safe-area-inset-bottom))" },
  sticky: { position: "sticky", top: 0, zIndex: 50, background: "rgba(244,244,244,.98)", backdropFilter: "blur(12px)", padding: "8px 14px 10px", borderBottom: "1px solid #ececec" },
  brandLock: { display: "flex", alignItems: "center", gap: 10 },
  brandName: { fontFamily: "'Cairo',sans-serif", fontSize: 15, fontWeight: 800, lineHeight: 1.3, color: night, margin: 0 },
  stickyRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginTop: 8 },
  stickyHello: { fontSize: 13, fontWeight: 700, color: "#666", flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  stickyBtns: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0, flexWrap: "wrap", justifyContent: "flex-end" },
  stickyGhost: { background: "#fff", border: "1.5px solid #e6e6e6", color: night, borderRadius: 10, padding: "6px 10px", fontSize: 12.5, fontWeight: 700, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  notifyBar: { marginTop: 10, background: "#fff", border: "1.5px solid #e6e6e6", borderRadius: 14, padding: "10px 12px", display: "grid", gap: 8 },
  notifyText: { fontSize: 13, fontWeight: 700, color: night, lineHeight: 1.45 },
  notifyActs: { display: "flex", gap: 8, flexWrap: "wrap" },
  notifyBtn: { border: "none", background: accent, color: "#fff", borderRadius: 10, padding: "7px 12px", fontSize: 13, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  notifySkip: { border: "1.5px solid #e6e6e6", background: "#fff", color: night, borderRadius: 10, padding: "7px 12px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  installScrim: { position: "fixed", inset: 0, zIndex: 90, background: "rgba(0,0,0,.55)", display: "flex", alignItems: "flex-end", justifyContent: "center", padding: 0 },
  installCard: { width: "100%", maxWidth: 430, background: "#fff", borderRadius: "22px 22px 0 0", padding: "18px 18px calc(18px + env(safe-area-inset-bottom))", display: "grid", gap: 10, boxShadow: "0 -18px 50px -18px rgba(0,0,0,.45)" },
  installIcon: { width: 44, height: 44, borderRadius: 12, background: "#FFF1EA", color: accent, display: "grid", placeItems: "center" },
  installTitle: { margin: 0, fontSize: 20, fontWeight: 800, color: night, fontFamily: "'Cairo',sans-serif", lineHeight: 1.3 },
  installText: { margin: 0, fontSize: 14, fontWeight: 600, color: "#666", lineHeight: 1.5 },
  installActs: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 4 },
  top: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 18px 6px", gap: 10 },
  topLoc: { flex: 1, minWidth: 0, textAlign: "right" },
  locLabel: { display: "block", fontSize: 11, color: fog, fontWeight: 600 },
  locVal: { display: "block", fontSize: 14, fontWeight: 800, color: night, lineHeight: 1.3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  iconBtn: { width: 42, height: 42, border: "none", background: "transparent", color: night, display: "grid", placeItems: "center", cursor: "pointer", position: "relative", padding: 0 },
  bagDot: { position: "absolute", top: 6, left: 6, minWidth: 16, height: 16, padding: "0 4px", borderRadius: 999, background: accent, color: "#fff", fontSize: 10, fontWeight: 800, display: "grid", placeItems: "center" },
  hero: { padding: "8px 20px 12px" },
  heroA: { margin: 0, fontSize: "clamp(26px, 8vw, 34px)", fontWeight: 800, lineHeight: 1.15, color: night },
  heroB: { margin: 0, fontSize: "clamp(26px, 8vw, 34px)", fontWeight: 500, lineHeight: 1.15, color: "#B3B3B3" },
  search: { margin: "4px 18px 16px", display: "flex", alignItems: "center", gap: 10, background: "#EFEFEF", borderRadius: 18, padding: "12px 14px" },
  searchInput: { flex: 1, border: "none", background: "transparent", fontSize: 15, fontFamily: "'Cairo','DM Sans',sans-serif", color: night, outline: "none", minWidth: 0 },
  searchClear: { border: "none", background: "transparent", color: fog, display: "grid", placeItems: "center", cursor: "pointer", padding: 2, flexShrink: 0 },
  searchHint: { gridColumn: "1 / -1", margin: "0 4px 0", fontSize: 13, fontWeight: 800, color: fog, textAlign: "right" },
  catBand: { margin: "0 14px 8px", background: "#EDEDED", borderRadius: 32, padding: "14px 6px 12px" },
  catRail: { display: "flex", gap: 4, overflowX: "auto", padding: "0 6px" },
  catBtn: { flexShrink: 0, width: 68, border: "none", background: "transparent", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 6, padding: "0 2px", fontFamily: "'Cairo',sans-serif" },
  catImg: { width: 52, height: 52, borderRadius: "50%", objectFit: "cover", background: "#fff", boxShadow: "0 4px 12px rgba(0,0,0,.08)", transition: "transform .18s ease" },
  catImgOn: { transform: "scale(1.12)", boxShadow: "0 6px 16px rgba(0,0,0,.14)" },
  catName: { fontSize: 11, fontWeight: 700, color: "#666" },
  catNameOn: { color: night, fontWeight: 800 },
  catLine: { width: 18, height: 3, borderRadius: 3, background: night, marginTop: -2 },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, padding: "12px 16px 8px" },
  card: { background: "#fff", border: "none", borderRadius: 22, padding: "8px 10px 12px", textAlign: "right", cursor: "pointer", fontFamily: "'Cairo',sans-serif", color: night, boxShadow: "0 10px 28px -18px rgba(0,0,0,.35)", display: "flex", flexDirection: "column", alignItems: "stretch" },
  cardImgWrap: { height: 118, display: "grid", placeItems: "center", marginTop: -6 },
  cardImg: { width: 108, height: 108, borderRadius: "50%", objectFit: "cover", display: "block" },
  cardQty: { position: "absolute", top: 8, left: 8, minWidth: 22, height: 22, padding: "0 6px", borderRadius: 999, background: night, color: "#fff", fontSize: 11, fontWeight: 800, display: "grid", placeItems: "center" },
  cardName: { fontSize: 14.5, fontWeight: 800, lineHeight: 1.3, margin: "2px 4px 0" },
  cardSub: { fontSize: 11.5, color: fog, margin: "2px 4px 10px", minHeight: 16 },
  cardFoot: { display: "flex", alignItems: "center", justifyContent: "flex-end", padding: "0 4px" },
  plus: { width: 32, height: 32, borderRadius: 10, border: "none", background: "#F0F0F0", color: night, display: "grid", placeItems: "center", cursor: "pointer" },
  dock: { position: "fixed", left: "50%", bottom: "calc(10px + env(safe-area-inset-bottom))", transform: "translateX(-50%)", zIndex: 40, display: "flex", gap: 6, background: night, borderRadius: 999, padding: "8px 10px", boxShadow: "0 14px 40px rgba(0,0,0,.28)", maxWidth: "calc(100% - 20px)" },
  dockBtn: { width: 46, height: 46, borderRadius: "50%", border: "none", background: "transparent", color: "#fff", display: "grid", placeItems: "center", cursor: "pointer", position: "relative" },
  dockDot: { position: "absolute", top: 2, left: 2, minWidth: 18, height: 18, padding: "0 5px", borderRadius: 999, background: accent, color: "#fff", fontSize: 10, fontWeight: 800, display: "grid", placeItems: "center", lineHeight: 1 },
  dockOn: { background: accent },
  detail: { position: "fixed", top: 0, bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, zIndex: 65, background: "#fff", overflowY: "auto", overflowX: "hidden", padding: "8px 16px 120px", WebkitOverflowScrolling: "touch" },
  detailTop: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 0 8px" },
  ghostIcon: { width: 40, height: 40, border: "none", background: "transparent", color: night, display: "grid", placeItems: "center", cursor: "pointer" },
  backBtn: { display: "inline-flex", alignItems: "center", gap: 6, border: "none", background: "transparent", color: night, fontFamily: "'Cairo',sans-serif", fontWeight: 800, fontSize: 15, padding: "8px 2px", cursor: "pointer" },
  detailHero: { display: "flex", flexDirection: "column", alignItems: "stretch", marginTop: 4 },
  detailTitle: { margin: 0, fontSize: "clamp(22px, 7vw, 28px)", fontWeight: 800, lineHeight: 1.25, color: night },
  detailSub: { margin: "8px 0 0", fontSize: 15, color: fog, fontWeight: 600 },
  detailStars: { display: "flex", alignItems: "center", gap: 4, marginTop: 12 },
  starScore: { fontSize: 13, color: fog, fontWeight: 700, marginRight: 4 },
  detailPrice: { margin: "12px 0 0", fontSize: 26, fontWeight: 800, color: accent },
  detailImgWrap: { display: "grid", placeItems: "center", margin: "28px 0 8px" },
  detailImg: { width: "min(180px, 46vw)", height: "min(180px, 46vw)", borderRadius: "50%", objectFit: "cover", display: "block", boxShadow: "0 18px 40px -20px rgba(0,0,0,.35)" },
  sizeLab: { margin: "22px 0 10px", fontSize: 16, fontWeight: 800 },
  sizeRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  sizeChip: { border: "none", background: "#F0F0F0", color: night, borderRadius: 12, padding: "10px 16px", fontSize: 14, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  sizeOn: { background: accent, color: "#fff" },
  detailNote: { marginTop: 22, fontSize: 13.5, color: fog, lineHeight: 1.7 },
  detailBar: { position: "fixed", left: "50%", bottom: 0, transform: "translateX(-50%)", width: "100%", maxWidth: 430, background: "#fff", display: "flex", gap: 10, alignItems: "center", padding: "12px 16px calc(14px + env(safe-area-inset-bottom))", boxShadow: "0 -10px 30px rgba(0,0,0,.08)", zIndex: 66 },
  qtyPill: { display: "flex", alignItems: "center", gap: 8, background: "#F0F0F0", borderRadius: 14, padding: "8px 10px", flexShrink: 0 },
  qtyBtn: { width: 28, height: 28, border: "none", background: "transparent", color: night, display: "grid", placeItems: "center", cursor: "pointer" },
  addCart: { flex: 1, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, background: night, color: "#fff", border: "none", borderRadius: 16, padding: "14px 12px", fontSize: 15, fontWeight: 800, cursor: "pointer", fontFamily: "'Cairo',sans-serif" },
  sheetScrim: { position: "fixed", inset: 0, zIndex: 58, background: "rgba(0,0,0,.4)" },
  sheet: { position: "absolute", left: "50%", bottom: 0, transform: "translateX(-50%)", width: "100%", maxWidth: 430, maxHeight: "92dvh", background: "#fff", borderRadius: "28px 28px 0 0", padding: "14px 16px 0", display: "flex", flexDirection: "column", overflow: "hidden" },
  sheetGrab: { width: 42, height: 4, borderRadius: 4, background: "#E0E0E0", margin: "0 auto 12px", flexShrink: 0 },
  sheetHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 8, flexShrink: 0 },
  sheetTitle: { margin: 0, fontSize: 20, fontWeight: 800, textAlign: "right", flex: 1 },
  sheetBody: { flex: 1, minHeight: 0, overflowY: "auto", WebkitOverflowScrolling: "touch", paddingBottom: 8 },
  sheetBar: { flexShrink: 0, padding: "10px 0 calc(16px + env(safe-area-inset-bottom))", borderTop: "1px solid #ececec", background: "#fff" },
  hist: { padding: "8px 16px 20px", display: "grid", gap: 12 },
};
